package org.scalingmq.demo.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProduceMsgRes.proto

public final class ProduceResWrapper {
  private ProduceResWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProduceMsgResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProduceMsgRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The errorCode.
     */
    String getErrorCode();
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The bytes for errorCode.
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The errorMsg.
     */
    String getErrorMsg();
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();

    /**
     * <pre>
     * 消息偏移量
     * </pre>
     *
     * <code>int64 offset = 3;</code>
     * @return The offset.
     */
    long getOffset();

    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @return The msgId.
     */
    String getMsgId();
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();
  }
  /**
   * <pre>
   * 生产消息响应
   * </pre>
   *
   * Protobuf type {@code ProduceMsgRes}
   */
  public static final class ProduceMsgRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProduceMsgRes)
      ProduceMsgResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProduceMsgRes.newBuilder() to construct.
    private ProduceMsgRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProduceMsgRes() {
      errorCode_ = "";
      errorMsg_ = "";
      msgId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProduceMsgRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProduceMsgRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              errorCode_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            case 24: {

              offset_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProduceResWrapper.internal_static_ProduceMsgRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProduceResWrapper.internal_static_ProduceMsgRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProduceMsgRes.class, Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private volatile Object errorCode_;
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The errorCode.
     */
    @Override
    public String getErrorCode() {
      Object ref = errorCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The bytes for errorCode.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      Object ref = errorCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMSG_FIELD_NUMBER = 2;
    private volatile Object errorMsg_;
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The errorMsg.
     */
    @Override
    public String getErrorMsg() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSET_FIELD_NUMBER = 3;
    private long offset_;
    /**
     * <pre>
     * 消息偏移量
     * </pre>
     *
     * <code>int64 offset = 3;</code>
     * @return The offset.
     */
    @Override
    public long getOffset() {
      return offset_;
    }

    public static final int MSGID_FIELD_NUMBER = 4;
    private volatile Object msgId_;
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @return The msgId.
     */
    @Override
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string msgId = 4;</code>
     * @return The bytes for msgId.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getErrorCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMsg_);
      }
      if (offset_ != 0L) {
        output.writeInt64(3, offset_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getErrorCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMsg_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, offset_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProduceMsgRes)) {
        return super.equals(obj);
      }
      ProduceMsgRes other = (ProduceMsgRes) obj;

      if (!getErrorCode()
          .equals(other.getErrorCode())) return false;
      if (!getErrorMsg()
          .equals(other.getErrorMsg())) return false;
      if (getOffset()
          != other.getOffset()) return false;
      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode().hashCode();
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProduceMsgRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProduceMsgRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProduceMsgRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProduceMsgRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProduceMsgRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProduceMsgRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProduceMsgRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProduceMsgRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProduceMsgRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProduceMsgRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProduceMsgRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProduceMsgRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProduceMsgRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 生产消息响应
     * </pre>
     *
     * Protobuf type {@code ProduceMsgRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProduceMsgRes)
        ProduceMsgResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProduceResWrapper.internal_static_ProduceMsgRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProduceResWrapper.internal_static_ProduceMsgRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProduceMsgRes.class, Builder.class);
      }

      // Construct using ProduceResWrapper.ProduceMsgRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        errorCode_ = "";

        errorMsg_ = "";

        offset_ = 0L;

        msgId_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProduceResWrapper.internal_static_ProduceMsgRes_descriptor;
      }

      @Override
      public ProduceMsgRes getDefaultInstanceForType() {
        return ProduceMsgRes.getDefaultInstance();
      }

      @Override
      public ProduceMsgRes build() {
        ProduceMsgRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ProduceMsgRes buildPartial() {
        ProduceMsgRes result = new ProduceMsgRes(this);
        result.errorCode_ = errorCode_;
        result.errorMsg_ = errorMsg_;
        result.offset_ = offset_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProduceMsgRes) {
          return mergeFrom((ProduceMsgRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProduceMsgRes other) {
        if (other == ProduceMsgRes.getDefaultInstance()) return this;
        if (!other.getErrorCode().isEmpty()) {
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProduceMsgRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProduceMsgRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object errorCode_ = "";
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @return The errorCode.
       */
      public String getErrorCode() {
        Object ref = errorCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @return The bytes for errorCode.
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @param value The bytes for errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorCode_ = value;
        onChanged();
        return this;
      }

      private Object errorMsg_ = "";
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return The errorMsg.
       */
      public String getErrorMsg() {
        Object ref = errorMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return The bytes for errorMsg.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @param value The bytes for errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <pre>
       * 消息偏移量
       * </pre>
       *
       * <code>int64 offset = 3;</code>
       * @return The offset.
       */
      @Override
      public long getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * 消息偏移量
       * </pre>
       *
       * <code>int64 offset = 3;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息偏移量
       * </pre>
       *
       * <code>int64 offset = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private Object msgId_ = "";
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string msgId = 4;</code>
       * @return The msgId.
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string msgId = 4;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string msgId = 4;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string msgId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string msgId = 4;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProduceMsgRes)
    }

    // @@protoc_insertion_point(class_scope:ProduceMsgRes)
    private static final ProduceMsgRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProduceMsgRes();
    }

    public static ProduceMsgRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProduceMsgRes>
        PARSER = new com.google.protobuf.AbstractParser<ProduceMsgRes>() {
      @Override
      public ProduceMsgRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProduceMsgRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProduceMsgRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProduceMsgRes> getParserForType() {
      return PARSER;
    }

    @Override
    public ProduceMsgRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProduceMsgRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProduceMsgRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ProduceMsgRes.proto\"S\n\rProduceMsgRes\022\021" +
      "\n\terrorCode\030\001 \001(\t\022\020\n\010errorMsg\030\002 \001(\t\022\016\n\006o" +
      "ffset\030\003 \001(\003\022\r\n\005msgId\030\004 \001(\tB\023B\021ProduceRes" +
      "Wrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProduceMsgRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProduceMsgRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProduceMsgRes_descriptor,
        new String[] { "ErrorCode", "ErrorMsg", "Offset", "MsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
