apiVersion: v1
kind: Pod
metadata:
  namespace: scalingmq
  name: client-sidercar
  labels:
    app: client-sidercar
spec:
  containers:
    - name: client-sidercar
      image: scalingmq-client-sidecar:v1.0
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      env:
        - name: BROKER_PORT
          value: "6543"
        - name: LANG
          value: en_US.UTF-8
  restartPolicy: Always
