---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scalingmq
  name: scalingmq-broker
  labels:
    app: scalingmq-broker
spec:
  replicas: 2
  template:
    metadata:
      name: scalingmq-broker
      labels:
        app: scalingmq-broker
    spec:
      containers:
        - name: scalingmq-broker
          image: scalingmq-broker-component:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7654
              name: http-port
            - containerPort: 6543
              name: rpc-port
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: ROUTE_SERVER_ADDR
              value: "scalingmq-route-service"
            - name: ROUTE_SERVER_PORT
              value: "5432"
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: C.UTF-8
      restartPolicy: Always
  selector:
    matchLabels:
      app: scalingmq-broker
---
apiVersion: v1
kind: Service
metadata:
  namespace: scalingmq
  name: scalingmq-broker-service
  labels:
    app: scalingmq-broker
spec:
  selector:
    app: scalingmq-broker
  ports:
    - port: 7654
      name: http-port
    - port: 6543
      name: rpc-port
  type: NodePort