package org.scalingmq.storage.core.replicate.raft.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftResponse.proto

public final class RaftResWrapper {
  private RaftResWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RaftResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RaftRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RaftRes.ResType resType = 1;</code>
     * @return The enum numeric value on the wire for resType.
     */
    int getResTypeValue();
    /**
     * <code>.RaftRes.ResType resType = 1;</code>
     * @return The resType.
     */
    RaftRes.ResType getResType();

    /**
     * <code>.RaftVoteRes raftVoteRes = 2;</code>
     * @return Whether the raftVoteRes field is set.
     */
    boolean hasRaftVoteRes();
    /**
     * <code>.RaftVoteRes raftVoteRes = 2;</code>
     * @return The raftVoteRes.
     */
    RaftVoteResWrapper.RaftVoteRes getRaftVoteRes();
    /**
     * <code>.RaftVoteRes raftVoteRes = 2;</code>
     */
    RaftVoteResWrapper.RaftVoteResOrBuilder getRaftVoteResOrBuilder();

    /**
     * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
     * @return Whether the raftHeartbeatRes field is set.
     */
    boolean hasRaftHeartbeatRes();
    /**
     * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
     * @return The raftHeartbeatRes.
     */
    RaftHeartbeatResWrapper.RaftHeartbeatRes getRaftHeartbeatRes();
    /**
     * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
     */
    RaftHeartbeatResWrapper.RaftHeartbeatResOrBuilder getRaftHeartbeatResOrBuilder();
  }
  /**
   * Protobuf type {@code RaftRes}
   */
  public static final class RaftRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RaftRes)
      RaftResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RaftRes.newBuilder() to construct.
    private RaftRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RaftRes() {
      resType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RaftRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RaftRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              resType_ = rawValue;
              break;
            }
            case 18: {
              RaftVoteResWrapper.RaftVoteRes.Builder subBuilder = null;
              if (raftVoteRes_ != null) {
                subBuilder = raftVoteRes_.toBuilder();
              }
              raftVoteRes_ = input.readMessage(RaftVoteResWrapper.RaftVoteRes.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(raftVoteRes_);
                raftVoteRes_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              RaftHeartbeatResWrapper.RaftHeartbeatRes.Builder subBuilder = null;
              if (raftHeartbeatRes_ != null) {
                subBuilder = raftHeartbeatRes_.toBuilder();
              }
              raftHeartbeatRes_ = input.readMessage(RaftHeartbeatResWrapper.RaftHeartbeatRes.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(raftHeartbeatRes_);
                raftHeartbeatRes_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RaftResWrapper.internal_static_RaftRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RaftResWrapper.internal_static_RaftRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RaftRes.class, Builder.class);
    }

    /**
     * Protobuf enum {@code RaftRes.ResType}
     */
    public enum ResType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 选票
       * </pre>
       *
       * <code>VOTE_RES = 0;</code>
       */
      VOTE_RES(0),
      /**
       * <pre>
       * 心跳
       * </pre>
       *
       * <code>HEART_RES = 1;</code>
       */
      HEART_RES(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 选票
       * </pre>
       *
       * <code>VOTE_RES = 0;</code>
       */
      public static final int VOTE_RES_VALUE = 0;
      /**
       * <pre>
       * 心跳
       * </pre>
       *
       * <code>HEART_RES = 1;</code>
       */
      public static final int HEART_RES_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ResType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ResType forNumber(int value) {
        switch (value) {
          case 0: return VOTE_RES;
          case 1: return HEART_RES;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResType>() {
              public ResType findValueByNumber(int number) {
                return ResType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RaftRes.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResType[] VALUES = values();

      public static ResType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RaftRes.ResType)
    }

    public static final int RESTYPE_FIELD_NUMBER = 1;
    private int resType_;
    /**
     * <code>.RaftRes.ResType resType = 1;</code>
     * @return The enum numeric value on the wire for resType.
     */
    @Override public int getResTypeValue() {
      return resType_;
    }
    /**
     * <code>.RaftRes.ResType resType = 1;</code>
     * @return The resType.
     */
    @Override public ResType getResType() {
      @SuppressWarnings("deprecation")
      ResType result = ResType.valueOf(resType_);
      return result == null ? ResType.UNRECOGNIZED : result;
    }

    public static final int RAFTVOTERES_FIELD_NUMBER = 2;
    private RaftVoteResWrapper.RaftVoteRes raftVoteRes_;
    /**
     * <code>.RaftVoteRes raftVoteRes = 2;</code>
     * @return Whether the raftVoteRes field is set.
     */
    @Override
    public boolean hasRaftVoteRes() {
      return raftVoteRes_ != null;
    }
    /**
     * <code>.RaftVoteRes raftVoteRes = 2;</code>
     * @return The raftVoteRes.
     */
    @Override
    public RaftVoteResWrapper.RaftVoteRes getRaftVoteRes() {
      return raftVoteRes_ == null ? RaftVoteResWrapper.RaftVoteRes.getDefaultInstance() : raftVoteRes_;
    }
    /**
     * <code>.RaftVoteRes raftVoteRes = 2;</code>
     */
    @Override
    public RaftVoteResWrapper.RaftVoteResOrBuilder getRaftVoteResOrBuilder() {
      return getRaftVoteRes();
    }

    public static final int RAFTHEARTBEATRES_FIELD_NUMBER = 3;
    private RaftHeartbeatResWrapper.RaftHeartbeatRes raftHeartbeatRes_;
    /**
     * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
     * @return Whether the raftHeartbeatRes field is set.
     */
    @Override
    public boolean hasRaftHeartbeatRes() {
      return raftHeartbeatRes_ != null;
    }
    /**
     * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
     * @return The raftHeartbeatRes.
     */
    @Override
    public RaftHeartbeatResWrapper.RaftHeartbeatRes getRaftHeartbeatRes() {
      return raftHeartbeatRes_ == null ? RaftHeartbeatResWrapper.RaftHeartbeatRes.getDefaultInstance() : raftHeartbeatRes_;
    }
    /**
     * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
     */
    @Override
    public RaftHeartbeatResWrapper.RaftHeartbeatResOrBuilder getRaftHeartbeatResOrBuilder() {
      return getRaftHeartbeatRes();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resType_ != ResType.VOTE_RES.getNumber()) {
        output.writeEnum(1, resType_);
      }
      if (raftVoteRes_ != null) {
        output.writeMessage(2, getRaftVoteRes());
      }
      if (raftHeartbeatRes_ != null) {
        output.writeMessage(3, getRaftHeartbeatRes());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resType_ != ResType.VOTE_RES.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resType_);
      }
      if (raftVoteRes_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRaftVoteRes());
      }
      if (raftHeartbeatRes_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRaftHeartbeatRes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RaftRes)) {
        return super.equals(obj);
      }
      RaftRes other = (RaftRes) obj;

      if (resType_ != other.resType_) return false;
      if (hasRaftVoteRes() != other.hasRaftVoteRes()) return false;
      if (hasRaftVoteRes()) {
        if (!getRaftVoteRes()
            .equals(other.getRaftVoteRes())) return false;
      }
      if (hasRaftHeartbeatRes() != other.hasRaftHeartbeatRes()) return false;
      if (hasRaftHeartbeatRes()) {
        if (!getRaftHeartbeatRes()
            .equals(other.getRaftHeartbeatRes())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESTYPE_FIELD_NUMBER;
      hash = (53 * hash) + resType_;
      if (hasRaftVoteRes()) {
        hash = (37 * hash) + RAFTVOTERES_FIELD_NUMBER;
        hash = (53 * hash) + getRaftVoteRes().hashCode();
      }
      if (hasRaftHeartbeatRes()) {
        hash = (37 * hash) + RAFTHEARTBEATRES_FIELD_NUMBER;
        hash = (53 * hash) + getRaftHeartbeatRes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RaftRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RaftRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RaftRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RaftRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RaftRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RaftRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RaftRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RaftRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RaftRes)
        RaftResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RaftResWrapper.internal_static_RaftRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RaftResWrapper.internal_static_RaftRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RaftRes.class, Builder.class);
      }

      // Construct using RaftResWrapper.RaftRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        resType_ = 0;

        if (raftVoteResBuilder_ == null) {
          raftVoteRes_ = null;
        } else {
          raftVoteRes_ = null;
          raftVoteResBuilder_ = null;
        }
        if (raftHeartbeatResBuilder_ == null) {
          raftHeartbeatRes_ = null;
        } else {
          raftHeartbeatRes_ = null;
          raftHeartbeatResBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RaftResWrapper.internal_static_RaftRes_descriptor;
      }

      @Override
      public RaftRes getDefaultInstanceForType() {
        return RaftRes.getDefaultInstance();
      }

      @Override
      public RaftRes build() {
        RaftRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RaftRes buildPartial() {
        RaftRes result = new RaftRes(this);
        result.resType_ = resType_;
        if (raftVoteResBuilder_ == null) {
          result.raftVoteRes_ = raftVoteRes_;
        } else {
          result.raftVoteRes_ = raftVoteResBuilder_.build();
        }
        if (raftHeartbeatResBuilder_ == null) {
          result.raftHeartbeatRes_ = raftHeartbeatRes_;
        } else {
          result.raftHeartbeatRes_ = raftHeartbeatResBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RaftRes) {
          return mergeFrom((RaftRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RaftRes other) {
        if (other == RaftRes.getDefaultInstance()) return this;
        if (other.resType_ != 0) {
          setResTypeValue(other.getResTypeValue());
        }
        if (other.hasRaftVoteRes()) {
          mergeRaftVoteRes(other.getRaftVoteRes());
        }
        if (other.hasRaftHeartbeatRes()) {
          mergeRaftHeartbeatRes(other.getRaftHeartbeatRes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RaftRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RaftRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int resType_ = 0;
      /**
       * <code>.RaftRes.ResType resType = 1;</code>
       * @return The enum numeric value on the wire for resType.
       */
      @Override public int getResTypeValue() {
        return resType_;
      }
      /**
       * <code>.RaftRes.ResType resType = 1;</code>
       * @param value The enum numeric value on the wire for resType to set.
       * @return This builder for chaining.
       */
      public Builder setResTypeValue(int value) {
        
        resType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RaftRes.ResType resType = 1;</code>
       * @return The resType.
       */
      @Override
      public ResType getResType() {
        @SuppressWarnings("deprecation")
        ResType result = ResType.valueOf(resType_);
        return result == null ? ResType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RaftRes.ResType resType = 1;</code>
       * @param value The resType to set.
       * @return This builder for chaining.
       */
      public Builder setResType(ResType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        resType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RaftRes.ResType resType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResType() {
        
        resType_ = 0;
        onChanged();
        return this;
      }

      private RaftVoteResWrapper.RaftVoteRes raftVoteRes_;
      private com.google.protobuf.SingleFieldBuilderV3<
          RaftVoteResWrapper.RaftVoteRes, RaftVoteResWrapper.RaftVoteRes.Builder, RaftVoteResWrapper.RaftVoteResOrBuilder> raftVoteResBuilder_;
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       * @return Whether the raftVoteRes field is set.
       */
      public boolean hasRaftVoteRes() {
        return raftVoteResBuilder_ != null || raftVoteRes_ != null;
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       * @return The raftVoteRes.
       */
      public RaftVoteResWrapper.RaftVoteRes getRaftVoteRes() {
        if (raftVoteResBuilder_ == null) {
          return raftVoteRes_ == null ? RaftVoteResWrapper.RaftVoteRes.getDefaultInstance() : raftVoteRes_;
        } else {
          return raftVoteResBuilder_.getMessage();
        }
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       */
      public Builder setRaftVoteRes(RaftVoteResWrapper.RaftVoteRes value) {
        if (raftVoteResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          raftVoteRes_ = value;
          onChanged();
        } else {
          raftVoteResBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       */
      public Builder setRaftVoteRes(
          RaftVoteResWrapper.RaftVoteRes.Builder builderForValue) {
        if (raftVoteResBuilder_ == null) {
          raftVoteRes_ = builderForValue.build();
          onChanged();
        } else {
          raftVoteResBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       */
      public Builder mergeRaftVoteRes(RaftVoteResWrapper.RaftVoteRes value) {
        if (raftVoteResBuilder_ == null) {
          if (raftVoteRes_ != null) {
            raftVoteRes_ =
              RaftVoteResWrapper.RaftVoteRes.newBuilder(raftVoteRes_).mergeFrom(value).buildPartial();
          } else {
            raftVoteRes_ = value;
          }
          onChanged();
        } else {
          raftVoteResBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       */
      public Builder clearRaftVoteRes() {
        if (raftVoteResBuilder_ == null) {
          raftVoteRes_ = null;
          onChanged();
        } else {
          raftVoteRes_ = null;
          raftVoteResBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       */
      public RaftVoteResWrapper.RaftVoteRes.Builder getRaftVoteResBuilder() {
        
        onChanged();
        return getRaftVoteResFieldBuilder().getBuilder();
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       */
      public RaftVoteResWrapper.RaftVoteResOrBuilder getRaftVoteResOrBuilder() {
        if (raftVoteResBuilder_ != null) {
          return raftVoteResBuilder_.getMessageOrBuilder();
        } else {
          return raftVoteRes_ == null ?
              RaftVoteResWrapper.RaftVoteRes.getDefaultInstance() : raftVoteRes_;
        }
      }
      /**
       * <code>.RaftVoteRes raftVoteRes = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RaftVoteResWrapper.RaftVoteRes, RaftVoteResWrapper.RaftVoteRes.Builder, RaftVoteResWrapper.RaftVoteResOrBuilder> 
          getRaftVoteResFieldBuilder() {
        if (raftVoteResBuilder_ == null) {
          raftVoteResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RaftVoteResWrapper.RaftVoteRes, RaftVoteResWrapper.RaftVoteRes.Builder, RaftVoteResWrapper.RaftVoteResOrBuilder>(
                  getRaftVoteRes(),
                  getParentForChildren(),
                  isClean());
          raftVoteRes_ = null;
        }
        return raftVoteResBuilder_;
      }

      private RaftHeartbeatResWrapper.RaftHeartbeatRes raftHeartbeatRes_;
      private com.google.protobuf.SingleFieldBuilderV3<
          RaftHeartbeatResWrapper.RaftHeartbeatRes, RaftHeartbeatResWrapper.RaftHeartbeatRes.Builder, RaftHeartbeatResWrapper.RaftHeartbeatResOrBuilder> raftHeartbeatResBuilder_;
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       * @return Whether the raftHeartbeatRes field is set.
       */
      public boolean hasRaftHeartbeatRes() {
        return raftHeartbeatResBuilder_ != null || raftHeartbeatRes_ != null;
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       * @return The raftHeartbeatRes.
       */
      public RaftHeartbeatResWrapper.RaftHeartbeatRes getRaftHeartbeatRes() {
        if (raftHeartbeatResBuilder_ == null) {
          return raftHeartbeatRes_ == null ? RaftHeartbeatResWrapper.RaftHeartbeatRes.getDefaultInstance() : raftHeartbeatRes_;
        } else {
          return raftHeartbeatResBuilder_.getMessage();
        }
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       */
      public Builder setRaftHeartbeatRes(RaftHeartbeatResWrapper.RaftHeartbeatRes value) {
        if (raftHeartbeatResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          raftHeartbeatRes_ = value;
          onChanged();
        } else {
          raftHeartbeatResBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       */
      public Builder setRaftHeartbeatRes(
          RaftHeartbeatResWrapper.RaftHeartbeatRes.Builder builderForValue) {
        if (raftHeartbeatResBuilder_ == null) {
          raftHeartbeatRes_ = builderForValue.build();
          onChanged();
        } else {
          raftHeartbeatResBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       */
      public Builder mergeRaftHeartbeatRes(RaftHeartbeatResWrapper.RaftHeartbeatRes value) {
        if (raftHeartbeatResBuilder_ == null) {
          if (raftHeartbeatRes_ != null) {
            raftHeartbeatRes_ =
              RaftHeartbeatResWrapper.RaftHeartbeatRes.newBuilder(raftHeartbeatRes_).mergeFrom(value).buildPartial();
          } else {
            raftHeartbeatRes_ = value;
          }
          onChanged();
        } else {
          raftHeartbeatResBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       */
      public Builder clearRaftHeartbeatRes() {
        if (raftHeartbeatResBuilder_ == null) {
          raftHeartbeatRes_ = null;
          onChanged();
        } else {
          raftHeartbeatRes_ = null;
          raftHeartbeatResBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       */
      public RaftHeartbeatResWrapper.RaftHeartbeatRes.Builder getRaftHeartbeatResBuilder() {
        
        onChanged();
        return getRaftHeartbeatResFieldBuilder().getBuilder();
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       */
      public RaftHeartbeatResWrapper.RaftHeartbeatResOrBuilder getRaftHeartbeatResOrBuilder() {
        if (raftHeartbeatResBuilder_ != null) {
          return raftHeartbeatResBuilder_.getMessageOrBuilder();
        } else {
          return raftHeartbeatRes_ == null ?
              RaftHeartbeatResWrapper.RaftHeartbeatRes.getDefaultInstance() : raftHeartbeatRes_;
        }
      }
      /**
       * <code>.RaftHeartbeatRes raftHeartbeatRes = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RaftHeartbeatResWrapper.RaftHeartbeatRes, RaftHeartbeatResWrapper.RaftHeartbeatRes.Builder, RaftHeartbeatResWrapper.RaftHeartbeatResOrBuilder> 
          getRaftHeartbeatResFieldBuilder() {
        if (raftHeartbeatResBuilder_ == null) {
          raftHeartbeatResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RaftHeartbeatResWrapper.RaftHeartbeatRes, RaftHeartbeatResWrapper.RaftHeartbeatRes.Builder, RaftHeartbeatResWrapper.RaftHeartbeatResOrBuilder>(
                  getRaftHeartbeatRes(),
                  getParentForChildren(),
                  isClean());
          raftHeartbeatRes_ = null;
        }
        return raftHeartbeatResBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RaftRes)
    }

    // @@protoc_insertion_point(class_scope:RaftRes)
    private static final RaftRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RaftRes();
    }

    public static RaftRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RaftRes>
        PARSER = new com.google.protobuf.AbstractParser<RaftRes>() {
      @Override
      public RaftRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RaftRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RaftRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RaftRes> getParserForType() {
      return PARSER;
    }

    @Override
    public RaftRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RaftRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RaftRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022RaftResponse.proto\032\033RaftHeartbeatRespo" +
      "nse.proto\032\026RaftVoteResponse.proto\"\244\001\n\007Ra" +
      "ftRes\022!\n\007resType\030\001 \001(\0162\020.RaftRes.ResType" +
      "\022!\n\013raftVoteRes\030\002 \001(\0132\014.RaftVoteRes\022+\n\020r" +
      "aftHeartbeatRes\030\003 \001(\0132\021.RaftHeartbeatRes" +
      "\"&\n\007ResType\022\014\n\010VOTE_RES\020\000\022\r\n\tHEART_RES\020\001" +
      "B\020B\016RaftResWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RaftHeartbeatResWrapper.getDescriptor(),
          RaftVoteResWrapper.getDescriptor(),
        });
    internal_static_RaftRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RaftRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RaftRes_descriptor,
        new String[] { "ResType", "RaftVoteRes", "RaftHeartbeatRes", });
    RaftHeartbeatResWrapper.getDescriptor();
    RaftVoteResWrapper.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
