package org.scalingmq.storage.core.replicate.raft.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftVoteResponse.proto

public final class RaftVoteResWrapper {
  private RaftVoteResWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RaftVoteResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RaftVoteRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The result.
     */
    RaftVoteResWrapper.RaftVoteRes.Result getResult();
  }
  /**
   * Protobuf type {@code RaftVoteRes}
   */
  public static final class RaftVoteRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RaftVoteRes)
      RaftVoteResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RaftVoteRes.newBuilder() to construct.
    private RaftVoteRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RaftVoteRes() {
      result_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RaftVoteRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RaftVoteRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RaftVoteResWrapper.internal_static_RaftVoteRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RaftVoteResWrapper.internal_static_RaftVoteRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RaftVoteResWrapper.RaftVoteRes.class, RaftVoteResWrapper.RaftVoteRes.Builder.class);
    }

    /**
     * Protobuf enum {@code RaftVoteRes.Result}
     */
    public enum Result
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACCEPT = 0;</code>
       */
      ACCEPT(0),
      /**
       * <code>REJECT = 1;</code>
       */
      REJECT(1),
      /**
       * <code>UNKNOWN = 2;</code>
       */
      UNKNOWN(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ACCEPT = 0;</code>
       */
      public static final int ACCEPT_VALUE = 0;
      /**
       * <code>REJECT = 1;</code>
       */
      public static final int REJECT_VALUE = 1;
      /**
       * <code>UNKNOWN = 2;</code>
       */
      public static final int UNKNOWN_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Result valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Result forNumber(int value) {
        switch (value) {
          case 0: return ACCEPT;
          case 1: return REJECT;
          case 2: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Result> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Result>() {
              public Result findValueByNumber(int number) {
                return Result.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RaftVoteResWrapper.RaftVoteRes.getDescriptor().getEnumTypes().get(0);
      }

      private static final Result[] VALUES = values();

      public static Result valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Result(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RaftVoteRes.Result)
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The result.
     */
    @java.lang.Override public RaftVoteResWrapper.RaftVoteRes.Result getResult() {
      @SuppressWarnings("deprecation")
      RaftVoteResWrapper.RaftVoteRes.Result result = RaftVoteResWrapper.RaftVoteRes.Result.valueOf(result_);
      return result == null ? RaftVoteResWrapper.RaftVoteRes.Result.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != RaftVoteResWrapper.RaftVoteRes.Result.ACCEPT.getNumber()) {
        output.writeEnum(1, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != RaftVoteResWrapper.RaftVoteRes.Result.ACCEPT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RaftVoteResWrapper.RaftVoteRes)) {
        return super.equals(obj);
      }
      RaftVoteResWrapper.RaftVoteRes other = (RaftVoteResWrapper.RaftVoteRes) obj;

      if (result_ != other.result_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RaftVoteResWrapper.RaftVoteRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RaftVoteResWrapper.RaftVoteRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RaftVoteRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RaftVoteRes)
        RaftVoteResWrapper.RaftVoteResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RaftVoteResWrapper.internal_static_RaftVoteRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RaftVoteResWrapper.internal_static_RaftVoteRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RaftVoteResWrapper.RaftVoteRes.class, RaftVoteResWrapper.RaftVoteRes.Builder.class);
      }

      // Construct using org.scalingmq.storage.core.replicate.raft.entity.RaftVoteResWrapper.RaftVoteRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RaftVoteResWrapper.internal_static_RaftVoteRes_descriptor;
      }

      @java.lang.Override
      public RaftVoteResWrapper.RaftVoteRes getDefaultInstanceForType() {
        return RaftVoteResWrapper.RaftVoteRes.getDefaultInstance();
      }

      @java.lang.Override
      public RaftVoteResWrapper.RaftVoteRes build() {
        RaftVoteResWrapper.RaftVoteRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RaftVoteResWrapper.RaftVoteRes buildPartial() {
        RaftVoteResWrapper.RaftVoteRes result = new RaftVoteResWrapper.RaftVoteRes(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RaftVoteResWrapper.RaftVoteRes) {
          return mergeFrom((RaftVoteResWrapper.RaftVoteRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RaftVoteResWrapper.RaftVoteRes other) {
        if (other == RaftVoteResWrapper.RaftVoteRes.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RaftVoteResWrapper.RaftVoteRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RaftVoteResWrapper.RaftVoteRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @java.lang.Override public int getResultValue() {
        return result_;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public RaftVoteResWrapper.RaftVoteRes.Result getResult() {
        @SuppressWarnings("deprecation")
        RaftVoteResWrapper.RaftVoteRes.Result result = RaftVoteResWrapper.RaftVoteRes.Result.valueOf(result_);
        return result == null ? RaftVoteResWrapper.RaftVoteRes.Result.UNRECOGNIZED : result;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(RaftVoteResWrapper.RaftVoteRes.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RaftVoteRes)
    }

    // @@protoc_insertion_point(class_scope:RaftVoteRes)
    private static final RaftVoteResWrapper.RaftVoteRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RaftVoteResWrapper.RaftVoteRes();
    }

    public static RaftVoteResWrapper.RaftVoteRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RaftVoteRes>
        PARSER = new com.google.protobuf.AbstractParser<RaftVoteRes>() {
      @java.lang.Override
      public RaftVoteRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RaftVoteRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RaftVoteRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RaftVoteRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RaftVoteResWrapper.RaftVoteRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RaftVoteRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RaftVoteRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RaftVoteResponse.proto\"a\n\013RaftVoteRes\022" +
      "#\n\006result\030\001 \001(\0162\023.RaftVoteRes.Result\"-\n\006" +
      "Result\022\n\n\006ACCEPT\020\000\022\n\n\006REJECT\020\001\022\013\n\007UNKNOW" +
      "N\020\002B\024B\022RaftVoteResWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RaftVoteRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RaftVoteRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RaftVoteRes_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
