package org.scalingmq.storage.core.replicate.raft.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftVoteResponse.proto

public final class RaftVoteResWrapper {
  private RaftVoteResWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RaftVoteResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RaftVoteRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The result.
     */
    RaftVoteRes.Result getResult();

    /**
     * <pre>
     * term过期
     * </pre>
     *
     * <code>int32 leaderId = 2;</code>
     * @return The leaderId.
     */
    int getLeaderId();

    /**
     * <code>int64 term = 3;</code>
     * @return The term.
     */
    long getTerm();
  }
  /**
   * Protobuf type {@code RaftVoteRes}
   */
  public static final class RaftVoteRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RaftVoteRes)
      RaftVoteResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RaftVoteRes.newBuilder() to construct.
    private RaftVoteRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RaftVoteRes() {
      result_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RaftVoteRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RaftVoteRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 16: {

              leaderId_ = input.readInt32();
              break;
            }
            case 24: {

              term_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RaftVoteResWrapper.internal_static_RaftVoteRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RaftVoteResWrapper.internal_static_RaftVoteRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RaftVoteRes.class, Builder.class);
    }

    /**
     * Protobuf enum {@code RaftVoteRes.Result}
     */
    public enum Result
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACCEPT = 0;</code>
       */
      ACCEPT(0),
      /**
       * <code>REJECT = 1;</code>
       */
      REJECT(1),
      /**
       * <code>TERM_EXPIRE = 2;</code>
       */
      TERM_EXPIRE(2),
      /**
       * <code>UNKNOWN = 3;</code>
       */
      UNKNOWN(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ACCEPT = 0;</code>
       */
      public static final int ACCEPT_VALUE = 0;
      /**
       * <code>REJECT = 1;</code>
       */
      public static final int REJECT_VALUE = 1;
      /**
       * <code>TERM_EXPIRE = 2;</code>
       */
      public static final int TERM_EXPIRE_VALUE = 2;
      /**
       * <code>UNKNOWN = 3;</code>
       */
      public static final int UNKNOWN_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Result valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Result forNumber(int value) {
        switch (value) {
          case 0: return ACCEPT;
          case 1: return REJECT;
          case 2: return TERM_EXPIRE;
          case 3: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Result> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Result>() {
              public Result findValueByNumber(int number) {
                return Result.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RaftVoteRes.getDescriptor().getEnumTypes().get(0);
      }

      private static final Result[] VALUES = values();

      public static Result valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Result(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RaftVoteRes.Result)
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.RaftVoteRes.Result result = 1;</code>
     * @return The result.
     */
    @Override public Result getResult() {
      @SuppressWarnings("deprecation")
      Result result = Result.valueOf(result_);
      return result == null ? Result.UNRECOGNIZED : result;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private int leaderId_;
    /**
     * <pre>
     * term过期
     * </pre>
     *
     * <code>int32 leaderId = 2;</code>
     * @return The leaderId.
     */
    @Override
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int TERM_FIELD_NUMBER = 3;
    private long term_;
    /**
     * <code>int64 term = 3;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != Result.ACCEPT.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (leaderId_ != 0) {
        output.writeInt32(2, leaderId_);
      }
      if (term_ != 0L) {
        output.writeInt64(3, term_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != Result.ACCEPT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (leaderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, leaderId_);
      }
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, term_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RaftVoteRes)) {
        return super.equals(obj);
      }
      RaftVoteRes other = (RaftVoteRes) obj;

      if (result_ != other.result_) return false;
      if (getLeaderId()
          != other.getLeaderId()) return false;
      if (getTerm()
          != other.getTerm()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + LEADERID_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderId();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RaftVoteRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftVoteRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftVoteRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftVoteRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftVoteRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RaftVoteRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RaftVoteRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RaftVoteRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RaftVoteRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RaftVoteRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RaftVoteRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RaftVoteRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RaftVoteRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RaftVoteRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RaftVoteRes)
        RaftVoteResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RaftVoteResWrapper.internal_static_RaftVoteRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RaftVoteResWrapper.internal_static_RaftVoteRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RaftVoteRes.class, Builder.class);
      }

      // Construct using RaftVoteResWrapper.RaftVoteRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        leaderId_ = 0;

        term_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RaftVoteResWrapper.internal_static_RaftVoteRes_descriptor;
      }

      @Override
      public RaftVoteRes getDefaultInstanceForType() {
        return RaftVoteRes.getDefaultInstance();
      }

      @Override
      public RaftVoteRes build() {
        RaftVoteRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RaftVoteRes buildPartial() {
        RaftVoteRes result = new RaftVoteRes(this);
        result.result_ = result_;
        result.leaderId_ = leaderId_;
        result.term_ = term_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RaftVoteRes) {
          return mergeFrom((RaftVoteRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RaftVoteRes other) {
        if (other == RaftVoteRes.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (other.getLeaderId() != 0) {
          setLeaderId(other.getLeaderId());
        }
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RaftVoteRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RaftVoteRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @Override public int getResultValue() {
        return result_;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @return The result.
       */
      @Override
      public Result getResult() {
        @SuppressWarnings("deprecation")
        Result result = Result.valueOf(result_);
        return result == null ? Result.UNRECOGNIZED : result;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RaftVoteRes.Result result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <pre>
       * term过期
       * </pre>
       *
       * <code>int32 leaderId = 2;</code>
       * @return The leaderId.
       */
      @Override
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <pre>
       * term过期
       * </pre>
       *
       * <code>int32 leaderId = 2;</code>
       * @param value The leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderId(int value) {
        
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * term过期
       * </pre>
       *
       * <code>int32 leaderId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderId() {
        
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private long term_ ;
      /**
       * <code>int64 term = 3;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 3;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RaftVoteRes)
    }

    // @@protoc_insertion_point(class_scope:RaftVoteRes)
    private static final RaftVoteRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RaftVoteRes();
    }

    public static RaftVoteRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RaftVoteRes>
        PARSER = new com.google.protobuf.AbstractParser<RaftVoteRes>() {
      @Override
      public RaftVoteRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RaftVoteRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RaftVoteRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RaftVoteRes> getParserForType() {
      return PARSER;
    }

    @Override
    public RaftVoteRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RaftVoteRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RaftVoteRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026RaftVoteResponse.proto\"\222\001\n\013RaftVoteRes" +
      "\022#\n\006result\030\001 \001(\0162\023.RaftVoteRes.Result\022\020\n" +
      "\010leaderId\030\002 \001(\005\022\014\n\004term\030\003 \001(\003\">\n\006Result\022" +
      "\n\n\006ACCEPT\020\000\022\n\n\006REJECT\020\001\022\017\n\013TERM_EXPIRE\020\002" +
      "\022\013\n\007UNKNOWN\020\003B\024B\022RaftVoteResWrapperb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RaftVoteRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RaftVoteRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RaftVoteRes_descriptor,
        new String[] { "Result", "LeaderId", "Term", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
