package org.scalingmq.broker.server.cons;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScalingmqRequset.proto

public final class ScalingmqReqWrapper {
  private ScalingmqReqWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScalingmqReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ScalingmqReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ScalingmqReq.ApiType apiType = 1;</code>
     * @return The enum numeric value on the wire for apiType.
     */
    int getApiTypeValue();
    /**
     * <code>.ScalingmqReq.ApiType apiType = 1;</code>
     * @return The apiType.
     */
    ScalingmqReq.ApiType getApiType();
  }
  /**
   * Protobuf type {@code ScalingmqReq}
   */
  public static final class ScalingmqReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ScalingmqReq)
      ScalingmqReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScalingmqReq.newBuilder() to construct.
    private ScalingmqReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScalingmqReq() {
      apiType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScalingmqReq();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScalingmqReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              apiType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ScalingmqReqWrapper.internal_static_ScalingmqReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ScalingmqReqWrapper.internal_static_ScalingmqReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScalingmqReq.class, Builder.class);
    }

    /**
     * Protobuf enum {@code ScalingmqReq.ApiType}
     */
    public enum ApiType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 生产消息
       * </pre>
       *
       * <code>PRODUCE = 0;</code>
       */
      PRODUCE(0),
      /**
       * <pre>
       * 消费获取消息
       * </pre>
       *
       * <code>FETCH = 1;</code>
       */
      FETCH(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 生产消息
       * </pre>
       *
       * <code>PRODUCE = 0;</code>
       */
      public static final int PRODUCE_VALUE = 0;
      /**
       * <pre>
       * 消费获取消息
       * </pre>
       *
       * <code>FETCH = 1;</code>
       */
      public static final int FETCH_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ApiType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ApiType forNumber(int value) {
        switch (value) {
          case 0: return PRODUCE;
          case 1: return FETCH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ApiType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ApiType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ApiType>() {
              public ApiType findValueByNumber(int number) {
                return ApiType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ScalingmqReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final ApiType[] VALUES = values();

      public static ApiType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ApiType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ScalingmqReq.ApiType)
    }

    public static final int APITYPE_FIELD_NUMBER = 1;
    private int apiType_;
    /**
     * <code>.ScalingmqReq.ApiType apiType = 1;</code>
     * @return The enum numeric value on the wire for apiType.
     */
    @Override public int getApiTypeValue() {
      return apiType_;
    }
    /**
     * <code>.ScalingmqReq.ApiType apiType = 1;</code>
     * @return The apiType.
     */
    @Override public ApiType getApiType() {
      @SuppressWarnings("deprecation")
      ApiType result = ApiType.valueOf(apiType_);
      return result == null ? ApiType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (apiType_ != ApiType.PRODUCE.getNumber()) {
        output.writeEnum(1, apiType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (apiType_ != ApiType.PRODUCE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, apiType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ScalingmqReq)) {
        return super.equals(obj);
      }
      ScalingmqReq other = (ScalingmqReq) obj;

      if (apiType_ != other.apiType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APITYPE_FIELD_NUMBER;
      hash = (53 * hash) + apiType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ScalingmqReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScalingmqReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScalingmqReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScalingmqReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScalingmqReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ScalingmqReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ScalingmqReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScalingmqReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScalingmqReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ScalingmqReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ScalingmqReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ScalingmqReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ScalingmqReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ScalingmqReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ScalingmqReq)
        ScalingmqReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ScalingmqReqWrapper.internal_static_ScalingmqReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ScalingmqReqWrapper.internal_static_ScalingmqReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ScalingmqReq.class, Builder.class);
      }

      // Construct using ScalingmqReqWrapper.ScalingmqReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        apiType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ScalingmqReqWrapper.internal_static_ScalingmqReq_descriptor;
      }

      @Override
      public ScalingmqReq getDefaultInstanceForType() {
        return ScalingmqReq.getDefaultInstance();
      }

      @Override
      public ScalingmqReq build() {
        ScalingmqReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ScalingmqReq buildPartial() {
        ScalingmqReq result = new ScalingmqReq(this);
        result.apiType_ = apiType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ScalingmqReq) {
          return mergeFrom((ScalingmqReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ScalingmqReq other) {
        if (other == ScalingmqReq.getDefaultInstance()) return this;
        if (other.apiType_ != 0) {
          setApiTypeValue(other.getApiTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ScalingmqReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ScalingmqReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int apiType_ = 0;
      /**
       * <code>.ScalingmqReq.ApiType apiType = 1;</code>
       * @return The enum numeric value on the wire for apiType.
       */
      @Override public int getApiTypeValue() {
        return apiType_;
      }
      /**
       * <code>.ScalingmqReq.ApiType apiType = 1;</code>
       * @param value The enum numeric value on the wire for apiType to set.
       * @return This builder for chaining.
       */
      public Builder setApiTypeValue(int value) {
        
        apiType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ScalingmqReq.ApiType apiType = 1;</code>
       * @return The apiType.
       */
      @Override
      public ApiType getApiType() {
        @SuppressWarnings("deprecation")
        ApiType result = ApiType.valueOf(apiType_);
        return result == null ? ApiType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ScalingmqReq.ApiType apiType = 1;</code>
       * @param value The apiType to set.
       * @return This builder for chaining.
       */
      public Builder setApiType(ApiType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        apiType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ScalingmqReq.ApiType apiType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearApiType() {
        
        apiType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ScalingmqReq)
    }

    // @@protoc_insertion_point(class_scope:ScalingmqReq)
    private static final ScalingmqReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ScalingmqReq();
    }

    public static ScalingmqReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScalingmqReq>
        PARSER = new com.google.protobuf.AbstractParser<ScalingmqReq>() {
      @Override
      public ScalingmqReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScalingmqReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScalingmqReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ScalingmqReq> getParserForType() {
      return PARSER;
    }

    @Override
    public ScalingmqReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScalingmqReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScalingmqReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026ScalingmqRequset.proto\"Y\n\014ScalingmqReq" +
      "\022&\n\007apiType\030\001 \001(\0162\025.ScalingmqReq.ApiType" +
      "\"!\n\007ApiType\022\013\n\007PRODUCE\020\000\022\t\n\005FETCH\020\001B\025B\023S" +
      "calingmqReqWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ScalingmqReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ScalingmqReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScalingmqReq_descriptor,
        new String[] { "ApiType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
