---
apiVersion: v1
kind: Namespace
metadata:
  name: scalingmq
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: scalingmq
  name: k8s-api-role
rules:
- apiGroups: [""]
  resources: ["namespaces","pods", "configmaps","services"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]

- apiGroups: [ "apps"]
  resources: ["deployments", "daemonsets", "statefulsets","replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: scalingmq
  name: k8s-api-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: scalingmq
  name: k8s-api-rollbinging
subjects:
- kind: ServiceAccount
  name: k8s-api-sa
  namespace: scalingmq
roleRef:
  kind: Role
  name: k8s-api-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scalingmq
  name: scalingmq-route
  labels:
    app: scalingmq-route
spec:
  replicas: 1
  template:
    metadata:
      name: scalingmq-route
      labels:
        app: scalingmq-route
    spec:
      containers:
        - name: scalingmq-route
          image: scalingmq-route-component:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: rpc-port
            - containerPort: 35555
              name: debug-port
          env:
            - name: SERVER_PORT
              value: "5432"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: en_US.UTF-8
            - name: SCHEDULE_STORAGE_POD_PORT
              value: "9876"
            - name: SCHEDULE_STORAGE_POD_IMAGE
              value: "scalingmq-storage-component:v1.0"
            - name: SCHEDULE_STORAGE_POD_CPU
              value: "500m"
            - name: SCHEDULE_STORAGE_POD_MEM
              value: "1Gi"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      serviceAccountName: k8s-api-sa
      restartPolicy: Always
  selector:
    matchLabels:
      app: scalingmq-route
---
apiVersion: v1
kind: Service
metadata:
  name: scalingmq-route-service
  namespace: scalingmq
  labels:
    app: scalingmq-route
spec:
  selector:
    app: scalingmq-route
  ports:
    - port: 5432
      name: rpc-port
    - port: 35555
      name: debug-port
  type: NodePort
---