package org.scalingmq.storage.api;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageApiRes.proto

public final class StorageApiResWrapper {
  private StorageApiResWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StorageApiResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StorageApiRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The errorCode.
     */
    String getErrorCode();
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The bytes for errorCode.
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The errorMsg.
     */
    String getErrorMsg();
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();

    /**
     * <pre>
     * 追加消息响应
     * </pre>
     *
     * <code>.PutMsgRes putMsgRes = 3;</code>
     * @return Whether the putMsgRes field is set.
     */
    boolean hasPutMsgRes();
    /**
     * <pre>
     * 追加消息响应
     * </pre>
     *
     * <code>.PutMsgRes putMsgRes = 3;</code>
     * @return The putMsgRes.
     */
    PutMsgRes getPutMsgRes();
    /**
     * <pre>
     * 追加消息响应
     * </pre>
     *
     * <code>.PutMsgRes putMsgRes = 3;</code>
     */
    PutMsgResOrBuilder getPutMsgResOrBuilder();

    /**
     * <pre>
     * 拉取消息响应
     * </pre>
     *
     * <code>.FetchMsgRes fetchMsgRes = 4;</code>
     * @return Whether the fetchMsgRes field is set.
     */
    boolean hasFetchMsgRes();
    /**
     * <pre>
     * 拉取消息响应
     * </pre>
     *
     * <code>.FetchMsgRes fetchMsgRes = 4;</code>
     * @return The fetchMsgRes.
     */
    FetchMsgRes getFetchMsgRes();
    /**
     * <pre>
     * 拉取消息响应
     * </pre>
     *
     * <code>.FetchMsgRes fetchMsgRes = 4;</code>
     */
    FetchMsgResOrBuilder getFetchMsgResOrBuilder();
  }
  /**
   * Protobuf type {@code StorageApiRes}
   */
  public static final class StorageApiRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StorageApiRes)
      StorageApiResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StorageApiRes.newBuilder() to construct.
    private StorageApiRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StorageApiRes() {
      errorCode_ = "";
      errorMsg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new StorageApiRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StorageApiRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              errorCode_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            case 26: {
              PutMsgRes.Builder subBuilder = null;
              if (putMsgRes_ != null) {
                subBuilder = putMsgRes_.toBuilder();
              }
              putMsgRes_ = input.readMessage(PutMsgRes.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(putMsgRes_);
                putMsgRes_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              FetchMsgRes.Builder subBuilder = null;
              if (fetchMsgRes_ != null) {
                subBuilder = fetchMsgRes_.toBuilder();
              }
              fetchMsgRes_ = input.readMessage(FetchMsgRes.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fetchMsgRes_);
                fetchMsgRes_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StorageApiResWrapper.internal_static_StorageApiRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StorageApiResWrapper.internal_static_StorageApiRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StorageApiRes.class, Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private volatile Object errorCode_;
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The errorCode.
     */
    @Override
    public String getErrorCode() {
      Object ref = errorCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>string errorCode = 1;</code>
     * @return The bytes for errorCode.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      Object ref = errorCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMSG_FIELD_NUMBER = 2;
    private volatile Object errorMsg_;
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The errorMsg.
     */
    @Override
    public String getErrorMsg() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUTMSGRES_FIELD_NUMBER = 3;
    private PutMsgRes putMsgRes_;
    /**
     * <pre>
     * 追加消息响应
     * </pre>
     *
     * <code>.PutMsgRes putMsgRes = 3;</code>
     * @return Whether the putMsgRes field is set.
     */
    @Override
    public boolean hasPutMsgRes() {
      return putMsgRes_ != null;
    }
    /**
     * <pre>
     * 追加消息响应
     * </pre>
     *
     * <code>.PutMsgRes putMsgRes = 3;</code>
     * @return The putMsgRes.
     */
    @Override
    public PutMsgRes getPutMsgRes() {
      return putMsgRes_ == null ? PutMsgRes.getDefaultInstance() : putMsgRes_;
    }
    /**
     * <pre>
     * 追加消息响应
     * </pre>
     *
     * <code>.PutMsgRes putMsgRes = 3;</code>
     */
    @Override
    public PutMsgResOrBuilder getPutMsgResOrBuilder() {
      return getPutMsgRes();
    }

    public static final int FETCHMSGRES_FIELD_NUMBER = 4;
    private FetchMsgRes fetchMsgRes_;
    /**
     * <pre>
     * 拉取消息响应
     * </pre>
     *
     * <code>.FetchMsgRes fetchMsgRes = 4;</code>
     * @return Whether the fetchMsgRes field is set.
     */
    @Override
    public boolean hasFetchMsgRes() {
      return fetchMsgRes_ != null;
    }
    /**
     * <pre>
     * 拉取消息响应
     * </pre>
     *
     * <code>.FetchMsgRes fetchMsgRes = 4;</code>
     * @return The fetchMsgRes.
     */
    @Override
    public FetchMsgRes getFetchMsgRes() {
      return fetchMsgRes_ == null ? FetchMsgRes.getDefaultInstance() : fetchMsgRes_;
    }
    /**
     * <pre>
     * 拉取消息响应
     * </pre>
     *
     * <code>.FetchMsgRes fetchMsgRes = 4;</code>
     */
    @Override
    public FetchMsgResOrBuilder getFetchMsgResOrBuilder() {
      return getFetchMsgRes();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getErrorCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMsg_);
      }
      if (putMsgRes_ != null) {
        output.writeMessage(3, getPutMsgRes());
      }
      if (fetchMsgRes_ != null) {
        output.writeMessage(4, getFetchMsgRes());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getErrorCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMsg_);
      }
      if (putMsgRes_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPutMsgRes());
      }
      if (fetchMsgRes_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getFetchMsgRes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StorageApiRes)) {
        return super.equals(obj);
      }
      StorageApiRes other = (StorageApiRes) obj;

      if (!getErrorCode()
          .equals(other.getErrorCode())) return false;
      if (!getErrorMsg()
          .equals(other.getErrorMsg())) return false;
      if (hasPutMsgRes() != other.hasPutMsgRes()) return false;
      if (hasPutMsgRes()) {
        if (!getPutMsgRes()
            .equals(other.getPutMsgRes())) return false;
      }
      if (hasFetchMsgRes() != other.hasFetchMsgRes()) return false;
      if (hasFetchMsgRes()) {
        if (!getFetchMsgRes()
            .equals(other.getFetchMsgRes())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode().hashCode();
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
      if (hasPutMsgRes()) {
        hash = (37 * hash) + PUTMSGRES_FIELD_NUMBER;
        hash = (53 * hash) + getPutMsgRes().hashCode();
      }
      if (hasFetchMsgRes()) {
        hash = (37 * hash) + FETCHMSGRES_FIELD_NUMBER;
        hash = (53 * hash) + getFetchMsgRes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StorageApiRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StorageApiRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StorageApiRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StorageApiRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StorageApiRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StorageApiRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StorageApiRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StorageApiRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StorageApiRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StorageApiRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StorageApiRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StorageApiRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StorageApiRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StorageApiRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StorageApiRes)
        StorageApiResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StorageApiResWrapper.internal_static_StorageApiRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StorageApiResWrapper.internal_static_StorageApiRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StorageApiRes.class, Builder.class);
      }

      // Construct using StorageApiResWrapper.StorageApiRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        errorCode_ = "";

        errorMsg_ = "";

        if (putMsgResBuilder_ == null) {
          putMsgRes_ = null;
        } else {
          putMsgRes_ = null;
          putMsgResBuilder_ = null;
        }
        if (fetchMsgResBuilder_ == null) {
          fetchMsgRes_ = null;
        } else {
          fetchMsgRes_ = null;
          fetchMsgResBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StorageApiResWrapper.internal_static_StorageApiRes_descriptor;
      }

      @Override
      public StorageApiRes getDefaultInstanceForType() {
        return StorageApiRes.getDefaultInstance();
      }

      @Override
      public StorageApiRes build() {
        StorageApiRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public StorageApiRes buildPartial() {
        StorageApiRes result = new StorageApiRes(this);
        result.errorCode_ = errorCode_;
        result.errorMsg_ = errorMsg_;
        if (putMsgResBuilder_ == null) {
          result.putMsgRes_ = putMsgRes_;
        } else {
          result.putMsgRes_ = putMsgResBuilder_.build();
        }
        if (fetchMsgResBuilder_ == null) {
          result.fetchMsgRes_ = fetchMsgRes_;
        } else {
          result.fetchMsgRes_ = fetchMsgResBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StorageApiRes) {
          return mergeFrom((StorageApiRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StorageApiRes other) {
        if (other == StorageApiRes.getDefaultInstance()) return this;
        if (!other.getErrorCode().isEmpty()) {
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        if (other.hasPutMsgRes()) {
          mergePutMsgRes(other.getPutMsgRes());
        }
        if (other.hasFetchMsgRes()) {
          mergeFetchMsgRes(other.getFetchMsgRes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StorageApiRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StorageApiRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object errorCode_ = "";
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @return The errorCode.
       */
      public String getErrorCode() {
        Object ref = errorCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @return The bytes for errorCode.
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>string errorCode = 1;</code>
       * @param value The bytes for errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorCode_ = value;
        onChanged();
        return this;
      }

      private Object errorMsg_ = "";
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return The errorMsg.
       */
      public String getErrorMsg() {
        Object ref = errorMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return The bytes for errorMsg.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @param value The bytes for errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }

      private PutMsgRes putMsgRes_;
      private com.google.protobuf.SingleFieldBuilderV3<
          PutMsgRes, PutMsgRes.Builder, PutMsgResOrBuilder> putMsgResBuilder_;
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       * @return Whether the putMsgRes field is set.
       */
      public boolean hasPutMsgRes() {
        return putMsgResBuilder_ != null || putMsgRes_ != null;
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       * @return The putMsgRes.
       */
      public PutMsgRes getPutMsgRes() {
        if (putMsgResBuilder_ == null) {
          return putMsgRes_ == null ? PutMsgRes.getDefaultInstance() : putMsgRes_;
        } else {
          return putMsgResBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       */
      public Builder setPutMsgRes(PutMsgRes value) {
        if (putMsgResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          putMsgRes_ = value;
          onChanged();
        } else {
          putMsgResBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       */
      public Builder setPutMsgRes(
          PutMsgRes.Builder builderForValue) {
        if (putMsgResBuilder_ == null) {
          putMsgRes_ = builderForValue.build();
          onChanged();
        } else {
          putMsgResBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       */
      public Builder mergePutMsgRes(PutMsgRes value) {
        if (putMsgResBuilder_ == null) {
          if (putMsgRes_ != null) {
            putMsgRes_ =
              PutMsgRes.newBuilder(putMsgRes_).mergeFrom(value).buildPartial();
          } else {
            putMsgRes_ = value;
          }
          onChanged();
        } else {
          putMsgResBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       */
      public Builder clearPutMsgRes() {
        if (putMsgResBuilder_ == null) {
          putMsgRes_ = null;
          onChanged();
        } else {
          putMsgRes_ = null;
          putMsgResBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       */
      public PutMsgRes.Builder getPutMsgResBuilder() {
        
        onChanged();
        return getPutMsgResFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       */
      public PutMsgResOrBuilder getPutMsgResOrBuilder() {
        if (putMsgResBuilder_ != null) {
          return putMsgResBuilder_.getMessageOrBuilder();
        } else {
          return putMsgRes_ == null ?
              PutMsgRes.getDefaultInstance() : putMsgRes_;
        }
      }
      /**
       * <pre>
       * 追加消息响应
       * </pre>
       *
       * <code>.PutMsgRes putMsgRes = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PutMsgRes, PutMsgRes.Builder, PutMsgResOrBuilder>
          getPutMsgResFieldBuilder() {
        if (putMsgResBuilder_ == null) {
          putMsgResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PutMsgRes, PutMsgRes.Builder, PutMsgResOrBuilder>(
                  getPutMsgRes(),
                  getParentForChildren(),
                  isClean());
          putMsgRes_ = null;
        }
        return putMsgResBuilder_;
      }

      private FetchMsgRes fetchMsgRes_;
      private com.google.protobuf.SingleFieldBuilderV3<
          FetchMsgRes, FetchMsgRes.Builder, FetchMsgResOrBuilder> fetchMsgResBuilder_;
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       * @return Whether the fetchMsgRes field is set.
       */
      public boolean hasFetchMsgRes() {
        return fetchMsgResBuilder_ != null || fetchMsgRes_ != null;
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       * @return The fetchMsgRes.
       */
      public FetchMsgRes getFetchMsgRes() {
        if (fetchMsgResBuilder_ == null) {
          return fetchMsgRes_ == null ? FetchMsgRes.getDefaultInstance() : fetchMsgRes_;
        } else {
          return fetchMsgResBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       */
      public Builder setFetchMsgRes(FetchMsgRes value) {
        if (fetchMsgResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fetchMsgRes_ = value;
          onChanged();
        } else {
          fetchMsgResBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       */
      public Builder setFetchMsgRes(
          FetchMsgRes.Builder builderForValue) {
        if (fetchMsgResBuilder_ == null) {
          fetchMsgRes_ = builderForValue.build();
          onChanged();
        } else {
          fetchMsgResBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       */
      public Builder mergeFetchMsgRes(FetchMsgRes value) {
        if (fetchMsgResBuilder_ == null) {
          if (fetchMsgRes_ != null) {
            fetchMsgRes_ =
              FetchMsgRes.newBuilder(fetchMsgRes_).mergeFrom(value).buildPartial();
          } else {
            fetchMsgRes_ = value;
          }
          onChanged();
        } else {
          fetchMsgResBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       */
      public Builder clearFetchMsgRes() {
        if (fetchMsgResBuilder_ == null) {
          fetchMsgRes_ = null;
          onChanged();
        } else {
          fetchMsgRes_ = null;
          fetchMsgResBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       */
      public FetchMsgRes.Builder getFetchMsgResBuilder() {
        
        onChanged();
        return getFetchMsgResFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       */
      public FetchMsgResOrBuilder getFetchMsgResOrBuilder() {
        if (fetchMsgResBuilder_ != null) {
          return fetchMsgResBuilder_.getMessageOrBuilder();
        } else {
          return fetchMsgRes_ == null ?
              FetchMsgRes.getDefaultInstance() : fetchMsgRes_;
        }
      }
      /**
       * <pre>
       * 拉取消息响应
       * </pre>
       *
       * <code>.FetchMsgRes fetchMsgRes = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FetchMsgRes, FetchMsgRes.Builder, FetchMsgResOrBuilder>
          getFetchMsgResFieldBuilder() {
        if (fetchMsgResBuilder_ == null) {
          fetchMsgResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FetchMsgRes, FetchMsgRes.Builder, FetchMsgResOrBuilder>(
                  getFetchMsgRes(),
                  getParentForChildren(),
                  isClean());
          fetchMsgRes_ = null;
        }
        return fetchMsgResBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StorageApiRes)
    }

    // @@protoc_insertion_point(class_scope:StorageApiRes)
    private static final StorageApiRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StorageApiRes();
    }

    public static StorageApiRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StorageApiRes>
        PARSER = new com.google.protobuf.AbstractParser<StorageApiRes>() {
      @Override
      public StorageApiRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StorageApiRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StorageApiRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StorageApiRes> getParserForType() {
      return PARSER;
    }

    @Override
    public StorageApiRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PutMsgResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PutMsgRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息偏移量
     * </pre>
     *
     * <code>int64 offset = 1;</code>
     * @return The offset.
     */
    long getOffset();

    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string msgId = 2;</code>
     * @return The msgId.
     */
    String getMsgId();
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string msgId = 2;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();
  }
  /**
   * <pre>
   * 追加消息响应
   * </pre>
   *
   * Protobuf type {@code PutMsgRes}
   */
  public static final class PutMsgRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PutMsgRes)
      PutMsgResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PutMsgRes.newBuilder() to construct.
    private PutMsgRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PutMsgRes() {
      msgId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PutMsgRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PutMsgRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              offset_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StorageApiResWrapper.internal_static_PutMsgRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StorageApiResWrapper.internal_static_PutMsgRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PutMsgRes.class, Builder.class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private long offset_;
    /**
     * <pre>
     * 消息偏移量
     * </pre>
     *
     * <code>int64 offset = 1;</code>
     * @return The offset.
     */
    @Override
    public long getOffset() {
      return offset_;
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private volatile Object msgId_;
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string msgId = 2;</code>
     * @return The msgId.
     */
    @Override
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string msgId = 2;</code>
     * @return The bytes for msgId.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offset_ != 0L) {
        output.writeInt64(1, offset_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, offset_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PutMsgRes)) {
        return super.equals(obj);
      }
      PutMsgRes other = (PutMsgRes) obj;

      if (getOffset()
          != other.getOffset()) return false;
      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PutMsgRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PutMsgRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PutMsgRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PutMsgRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PutMsgRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PutMsgRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PutMsgRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PutMsgRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PutMsgRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PutMsgRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PutMsgRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PutMsgRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PutMsgRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 追加消息响应
     * </pre>
     *
     * Protobuf type {@code PutMsgRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PutMsgRes)
        PutMsgResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StorageApiResWrapper.internal_static_PutMsgRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StorageApiResWrapper.internal_static_PutMsgRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PutMsgRes.class, Builder.class);
      }

      // Construct using StorageApiResWrapper.PutMsgRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        offset_ = 0L;

        msgId_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StorageApiResWrapper.internal_static_PutMsgRes_descriptor;
      }

      @Override
      public PutMsgRes getDefaultInstanceForType() {
        return PutMsgRes.getDefaultInstance();
      }

      @Override
      public PutMsgRes build() {
        PutMsgRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PutMsgRes buildPartial() {
        PutMsgRes result = new PutMsgRes(this);
        result.offset_ = offset_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PutMsgRes) {
          return mergeFrom((PutMsgRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PutMsgRes other) {
        if (other == PutMsgRes.getDefaultInstance()) return this;
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PutMsgRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PutMsgRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long offset_ ;
      /**
       * <pre>
       * 消息偏移量
       * </pre>
       *
       * <code>int64 offset = 1;</code>
       * @return The offset.
       */
      @Override
      public long getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * 消息偏移量
       * </pre>
       *
       * <code>int64 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息偏移量
       * </pre>
       *
       * <code>int64 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private Object msgId_ = "";
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string msgId = 2;</code>
       * @return The msgId.
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string msgId = 2;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string msgId = 2;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string msgId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string msgId = 2;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PutMsgRes)
    }

    // @@protoc_insertion_point(class_scope:PutMsgRes)
    private static final PutMsgRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PutMsgRes();
    }

    public static PutMsgRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PutMsgRes>
        PARSER = new com.google.protobuf.AbstractParser<PutMsgRes>() {
      @Override
      public PutMsgRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PutMsgRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PutMsgRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PutMsgRes> getParserForType() {
      return PARSER;
    }

    @Override
    public PutMsgRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FetchMsgResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FetchMsgRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 没有更多的数据标识
     * </pre>
     *
     * <code>bool alreadyLastOffset = 1;</code>
     * @return The alreadyLastOffset.
     */
    boolean getAlreadyLastOffset();

    /**
     * <pre>
     * 拉取到的数据
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     * 拉取到的数据最后的offset
     * </pre>
     *
     * <code>int64 fetchLastOffset = 3;</code>
     * @return The fetchLastOffset.
     */
    long getFetchLastOffset();
  }
  /**
   * <pre>
   * 拉取消息响应
   * </pre>
   *
   * Protobuf type {@code FetchMsgRes}
   */
  public static final class FetchMsgRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FetchMsgRes)
      FetchMsgResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FetchMsgRes.newBuilder() to construct.
    private FetchMsgRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchMsgRes() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new FetchMsgRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FetchMsgRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              alreadyLastOffset_ = input.readBool();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 24: {

              fetchLastOffset_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StorageApiResWrapper.internal_static_FetchMsgRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StorageApiResWrapper.internal_static_FetchMsgRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FetchMsgRes.class, Builder.class);
    }

    public static final int ALREADYLASTOFFSET_FIELD_NUMBER = 1;
    private boolean alreadyLastOffset_;
    /**
     * <pre>
     * 没有更多的数据标识
     * </pre>
     *
     * <code>bool alreadyLastOffset = 1;</code>
     * @return The alreadyLastOffset.
     */
    @Override
    public boolean getAlreadyLastOffset() {
      return alreadyLastOffset_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * 拉取到的数据
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int FETCHLASTOFFSET_FIELD_NUMBER = 3;
    private long fetchLastOffset_;
    /**
     * <pre>
     * 拉取到的数据最后的offset
     * </pre>
     *
     * <code>int64 fetchLastOffset = 3;</code>
     * @return The fetchLastOffset.
     */
    @Override
    public long getFetchLastOffset() {
      return fetchLastOffset_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (alreadyLastOffset_ != false) {
        output.writeBool(1, alreadyLastOffset_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (fetchLastOffset_ != 0L) {
        output.writeInt64(3, fetchLastOffset_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (alreadyLastOffset_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, alreadyLastOffset_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (fetchLastOffset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fetchLastOffset_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FetchMsgRes)) {
        return super.equals(obj);
      }
      FetchMsgRes other = (FetchMsgRes) obj;

      if (getAlreadyLastOffset()
          != other.getAlreadyLastOffset()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getFetchLastOffset()
          != other.getFetchLastOffset()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALREADYLASTOFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAlreadyLastOffset());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + FETCHLASTOFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFetchLastOffset());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FetchMsgRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMsgRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMsgRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMsgRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMsgRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMsgRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMsgRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FetchMsgRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FetchMsgRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FetchMsgRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FetchMsgRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FetchMsgRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FetchMsgRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 拉取消息响应
     * </pre>
     *
     * Protobuf type {@code FetchMsgRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FetchMsgRes)
        FetchMsgResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StorageApiResWrapper.internal_static_FetchMsgRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StorageApiResWrapper.internal_static_FetchMsgRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FetchMsgRes.class, Builder.class);
      }

      // Construct using StorageApiResWrapper.FetchMsgRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        alreadyLastOffset_ = false;

        data_ = com.google.protobuf.ByteString.EMPTY;

        fetchLastOffset_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StorageApiResWrapper.internal_static_FetchMsgRes_descriptor;
      }

      @Override
      public FetchMsgRes getDefaultInstanceForType() {
        return FetchMsgRes.getDefaultInstance();
      }

      @Override
      public FetchMsgRes build() {
        FetchMsgRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FetchMsgRes buildPartial() {
        FetchMsgRes result = new FetchMsgRes(this);
        result.alreadyLastOffset_ = alreadyLastOffset_;
        result.data_ = data_;
        result.fetchLastOffset_ = fetchLastOffset_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FetchMsgRes) {
          return mergeFrom((FetchMsgRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FetchMsgRes other) {
        if (other == FetchMsgRes.getDefaultInstance()) return this;
        if (other.getAlreadyLastOffset() != false) {
          setAlreadyLastOffset(other.getAlreadyLastOffset());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getFetchLastOffset() != 0L) {
          setFetchLastOffset(other.getFetchLastOffset());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FetchMsgRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FetchMsgRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean alreadyLastOffset_ ;
      /**
       * <pre>
       * 没有更多的数据标识
       * </pre>
       *
       * <code>bool alreadyLastOffset = 1;</code>
       * @return The alreadyLastOffset.
       */
      @Override
      public boolean getAlreadyLastOffset() {
        return alreadyLastOffset_;
      }
      /**
       * <pre>
       * 没有更多的数据标识
       * </pre>
       *
       * <code>bool alreadyLastOffset = 1;</code>
       * @param value The alreadyLastOffset to set.
       * @return This builder for chaining.
       */
      public Builder setAlreadyLastOffset(boolean value) {
        
        alreadyLastOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 没有更多的数据标识
       * </pre>
       *
       * <code>bool alreadyLastOffset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlreadyLastOffset() {
        
        alreadyLastOffset_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 拉取到的数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * 拉取到的数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 拉取到的数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long fetchLastOffset_ ;
      /**
       * <pre>
       * 拉取到的数据最后的offset
       * </pre>
       *
       * <code>int64 fetchLastOffset = 3;</code>
       * @return The fetchLastOffset.
       */
      @Override
      public long getFetchLastOffset() {
        return fetchLastOffset_;
      }
      /**
       * <pre>
       * 拉取到的数据最后的offset
       * </pre>
       *
       * <code>int64 fetchLastOffset = 3;</code>
       * @param value The fetchLastOffset to set.
       * @return This builder for chaining.
       */
      public Builder setFetchLastOffset(long value) {
        
        fetchLastOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 拉取到的数据最后的offset
       * </pre>
       *
       * <code>int64 fetchLastOffset = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFetchLastOffset() {
        
        fetchLastOffset_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FetchMsgRes)
    }

    // @@protoc_insertion_point(class_scope:FetchMsgRes)
    private static final FetchMsgRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FetchMsgRes();
    }

    public static FetchMsgRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchMsgRes>
        PARSER = new com.google.protobuf.AbstractParser<FetchMsgRes>() {
      @Override
      public FetchMsgRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchMsgRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchMsgRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FetchMsgRes> getParserForType() {
      return PARSER;
    }

    @Override
    public FetchMsgRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StorageApiRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StorageApiRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PutMsgRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PutMsgRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchMsgRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchMsgRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023StorageApiRes.proto\"v\n\rStorageApiRes\022\021" +
      "\n\terrorCode\030\001 \001(\t\022\020\n\010errorMsg\030\002 \001(\t\022\035\n\tp" +
      "utMsgRes\030\003 \001(\0132\n.PutMsgRes\022!\n\013fetchMsgRe" +
      "s\030\004 \001(\0132\014.FetchMsgRes\"*\n\tPutMsgRes\022\016\n\006of" +
      "fset\030\001 \001(\003\022\r\n\005msgId\030\002 \001(\t\"O\n\013FetchMsgRes" +
      "\022\031\n\021alreadyLastOffset\030\001 \001(\010\022\014\n\004data\030\002 \001(" +
      "\014\022\027\n\017fetchLastOffset\030\003 \001(\003B\026B\024StorageApi" +
      "ResWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StorageApiRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StorageApiRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StorageApiRes_descriptor,
        new String[] { "ErrorCode", "ErrorMsg", "PutMsgRes", "FetchMsgRes", });
    internal_static_PutMsgRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PutMsgRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PutMsgRes_descriptor,
        new String[] { "Offset", "MsgId", });
    internal_static_FetchMsgRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FetchMsgRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchMsgRes_descriptor,
        new String[] { "AlreadyLastOffset", "Data", "FetchLastOffset", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
