---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: scalingmq-demo
  ports:
    - port: 10000
      name: http
    - port: 35556
      name: debug
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: scalingmq-demo
  namespace: scalingmq
  labels:
    app: scalingmq-demo
spec:
  containers:
    - name: scalingmq-client-sidecar
      image: scalingmq-client-sidecar:v1.0
      volumeMounts:
        - mountPath: /sidecar
          name: sidercar-workspace
      securityContext:
        privileged: true
      env:
        - name: BROKER_PORT
          value: "6543"
        - name: LANG
          value: C.utf8
    - name: scalingmq-demo
      image: scalingmq-demo:v1.0
      env:
        - name: BROKER_PORT
          value: "6543"
        - name: BROKER_HOST
          value: "scalingmq-broker-service"
      ports:
        - containerPort: 10000
          name: http
        - containerPort: 35556
          name: debug
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  volumes:
    - name: sidercar-workspace
      hostPath:
        path: /Users/renyansong/scalingmq/sidecar
---