apiVersion: v1
kind: Pod
metadata:
  name: scalingmq-demo
  namespace: scalingmq
  labels:
    app: scalingmq-demo
spec:
  initContainers:
    - name: scalingmq-client-sidecar
      image: scalingmq-client-sidecar:v1.0
      volumeMounts:
        - mountPath: /sidecar
          name: sidercar-workspace
      securityContext:
        privileged: true
      env:
        - name: BROKER_PORT
          value: "6543"
        - name: LANG
          value: C.utf8
  containers:
    - name: scalingmq-demo
      image: scalingmq-demo:v1.0
      env:
        - name: BROKER_PORT
          value: "6543"
        - name: BROKER_HOST
          value: "scalingmq-broker-service"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  volumes:
    - name: sidercar-workspace
      hostPath:
        path: /Users/renyansong/scalingmq/sidecar
