package org.scalingmq.route.client.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteAPIResponse.proto

public final class RouteResWrapper {
  private RouteResWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RouteApiResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RouteApiRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误code
     * </pre>
     *
     * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    int getErrorCodeValue();
    /**
     * <pre>
     * 错误code
     * </pre>
     *
     * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
     * @return The errorCode.
     */
    RouteApiRes.ErrorCode getErrorCode();

    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The errorMsg.
     */
    String getErrorMsg();
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();

    /**
     * <pre>
     * topic元数据创建结果
     * </pre>
     *
     * <code>bool createTopicMetadataRes = 3;</code>
     * @return The createTopicMetadataRes.
     */
    boolean getCreateTopicMetadataRes();

    /**
     * <pre>
     * 获取元数据的响应结果
     * </pre>
     *
     * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
     * @return Whether the fetchTopicMetadataResult field is set.
     */
    boolean hasFetchTopicMetadataResult();
    /**
     * <pre>
     * 获取元数据的响应结果
     * </pre>
     *
     * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
     * @return The fetchTopicMetadataResult.
     */
    FetchTopicMetadataResultWrapper.FetchTopicMetadataResult getFetchTopicMetadataResult();
    /**
     * <pre>
     * 获取元数据的响应结果
     * </pre>
     *
     * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
     */
    FetchTopicMetadataResultWrapper.FetchTopicMetadataResultOrBuilder getFetchTopicMetadataResultOrBuilder();
  }
  /**
   * Protobuf type {@code RouteApiRes}
   */
  public static final class RouteApiRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RouteApiRes)
      RouteApiResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RouteApiRes.newBuilder() to construct.
    private RouteApiRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RouteApiRes() {
      errorCode_ = 0;
      errorMsg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RouteApiRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RouteApiRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              errorCode_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            case 24: {

              createTopicMetadataRes_ = input.readBool();
              break;
            }
            case 34: {
              FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.Builder subBuilder = null;
              if (fetchTopicMetadataResult_ != null) {
                subBuilder = fetchTopicMetadataResult_.toBuilder();
              }
              fetchTopicMetadataResult_ = input.readMessage(FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fetchTopicMetadataResult_);
                fetchTopicMetadataResult_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouteResWrapper.internal_static_RouteApiRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouteResWrapper.internal_static_RouteApiRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RouteApiRes.class, Builder.class);
    }

    /**
     * Protobuf enum {@code RouteApiRes.ErrorCode}
     */
    public enum ErrorCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 未知错误
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <pre>
       * 创建topic元数据失败
       * </pre>
       *
       * <code>CREATE_TOPIC_METADATA_FAIL = 1;</code>
       */
      CREATE_TOPIC_METADATA_FAIL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 未知错误
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * 创建topic元数据失败
       * </pre>
       *
       * <code>CREATE_TOPIC_METADATA_FAIL = 1;</code>
       */
      public static final int CREATE_TOPIC_METADATA_FAIL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ErrorCode valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ErrorCode forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return CREATE_TOPIC_METADATA_FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ErrorCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
              public ErrorCode findValueByNumber(int number) {
                return ErrorCode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RouteApiRes.getDescriptor().getEnumTypes().get(0);
      }

      private static final ErrorCode[] VALUES = values();

      public static ErrorCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ErrorCode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RouteApiRes.ErrorCode)
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <pre>
     * 错误code
     * </pre>
     *
     * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    @Override public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <pre>
     * 错误code
     * </pre>
     *
     * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
     * @return The errorCode.
     */
    @Override public ErrorCode getErrorCode() {
      @SuppressWarnings("deprecation")
      ErrorCode result = ErrorCode.valueOf(errorCode_);
      return result == null ? ErrorCode.UNRECOGNIZED : result;
    }

    public static final int ERRORMSG_FIELD_NUMBER = 2;
    private volatile Object errorMsg_;
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The errorMsg.
     */
    @Override
    public String getErrorMsg() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>string errorMsg = 2;</code>
     * @return The bytes for errorMsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETOPICMETADATARES_FIELD_NUMBER = 3;
    private boolean createTopicMetadataRes_;
    /**
     * <pre>
     * topic元数据创建结果
     * </pre>
     *
     * <code>bool createTopicMetadataRes = 3;</code>
     * @return The createTopicMetadataRes.
     */
    @Override
    public boolean getCreateTopicMetadataRes() {
      return createTopicMetadataRes_;
    }

    public static final int FETCHTOPICMETADATARESULT_FIELD_NUMBER = 4;
    private FetchTopicMetadataResultWrapper.FetchTopicMetadataResult fetchTopicMetadataResult_;
    /**
     * <pre>
     * 获取元数据的响应结果
     * </pre>
     *
     * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
     * @return Whether the fetchTopicMetadataResult field is set.
     */
    @Override
    public boolean hasFetchTopicMetadataResult() {
      return fetchTopicMetadataResult_ != null;
    }
    /**
     * <pre>
     * 获取元数据的响应结果
     * </pre>
     *
     * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
     * @return The fetchTopicMetadataResult.
     */
    @Override
    public FetchTopicMetadataResultWrapper.FetchTopicMetadataResult getFetchTopicMetadataResult() {
      return fetchTopicMetadataResult_ == null ? FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.getDefaultInstance() : fetchTopicMetadataResult_;
    }
    /**
     * <pre>
     * 获取元数据的响应结果
     * </pre>
     *
     * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
     */
    @Override
    public FetchTopicMetadataResultWrapper.FetchTopicMetadataResultOrBuilder getFetchTopicMetadataResultOrBuilder() {
      return getFetchTopicMetadataResult();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != ErrorCode.UNKNOWN.getNumber()) {
        output.writeEnum(1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMsg_);
      }
      if (createTopicMetadataRes_ != false) {
        output.writeBool(3, createTopicMetadataRes_);
      }
      if (fetchTopicMetadataResult_ != null) {
        output.writeMessage(4, getFetchTopicMetadataResult());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != ErrorCode.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMsg_);
      }
      if (createTopicMetadataRes_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, createTopicMetadataRes_);
      }
      if (fetchTopicMetadataResult_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getFetchTopicMetadataResult());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RouteApiRes)) {
        return super.equals(obj);
      }
      RouteApiRes other = (RouteApiRes) obj;

      if (errorCode_ != other.errorCode_) return false;
      if (!getErrorMsg()
          .equals(other.getErrorMsg())) return false;
      if (getCreateTopicMetadataRes()
          != other.getCreateTopicMetadataRes()) return false;
      if (hasFetchTopicMetadataResult() != other.hasFetchTopicMetadataResult()) return false;
      if (hasFetchTopicMetadataResult()) {
        if (!getFetchTopicMetadataResult()
            .equals(other.getFetchTopicMetadataResult())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + errorCode_;
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
      hash = (37 * hash) + CREATETOPICMETADATARES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCreateTopicMetadataRes());
      if (hasFetchTopicMetadataResult()) {
        hash = (37 * hash) + FETCHTOPICMETADATARESULT_FIELD_NUMBER;
        hash = (53 * hash) + getFetchTopicMetadataResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RouteApiRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteApiRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteApiRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteApiRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteApiRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteApiRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteApiRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RouteApiRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RouteApiRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RouteApiRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RouteApiRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RouteApiRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RouteApiRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RouteApiRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RouteApiRes)
        RouteApiResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RouteResWrapper.internal_static_RouteApiRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RouteResWrapper.internal_static_RouteApiRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RouteApiRes.class, Builder.class);
      }

      // Construct using RouteResWrapper.RouteApiRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        errorMsg_ = "";

        createTopicMetadataRes_ = false;

        if (fetchTopicMetadataResultBuilder_ == null) {
          fetchTopicMetadataResult_ = null;
        } else {
          fetchTopicMetadataResult_ = null;
          fetchTopicMetadataResultBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RouteResWrapper.internal_static_RouteApiRes_descriptor;
      }

      @Override
      public RouteApiRes getDefaultInstanceForType() {
        return RouteApiRes.getDefaultInstance();
      }

      @Override
      public RouteApiRes build() {
        RouteApiRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RouteApiRes buildPartial() {
        RouteApiRes result = new RouteApiRes(this);
        result.errorCode_ = errorCode_;
        result.errorMsg_ = errorMsg_;
        result.createTopicMetadataRes_ = createTopicMetadataRes_;
        if (fetchTopicMetadataResultBuilder_ == null) {
          result.fetchTopicMetadataResult_ = fetchTopicMetadataResult_;
        } else {
          result.fetchTopicMetadataResult_ = fetchTopicMetadataResultBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RouteApiRes) {
          return mergeFrom((RouteApiRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RouteApiRes other) {
        if (other == RouteApiRes.getDefaultInstance()) return this;
        if (other.errorCode_ != 0) {
          setErrorCodeValue(other.getErrorCodeValue());
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        if (other.getCreateTopicMetadataRes() != false) {
          setCreateTopicMetadataRes(other.getCreateTopicMetadataRes());
        }
        if (other.hasFetchTopicMetadataResult()) {
          mergeFetchTopicMetadataResult(other.getFetchTopicMetadataResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RouteApiRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RouteApiRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ = 0;
      /**
       * <pre>
       * 错误code
       * </pre>
       *
       * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
       * @return The enum numeric value on the wire for errorCode.
       */
      @Override public int getErrorCodeValue() {
        return errorCode_;
      }
      /**
       * <pre>
       * 错误code
       * </pre>
       *
       * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
       * @param value The enum numeric value on the wire for errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCodeValue(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误code
       * </pre>
       *
       * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
       * @return The errorCode.
       */
      @Override
      public ErrorCode getErrorCode() {
        @SuppressWarnings("deprecation")
        ErrorCode result = ErrorCode.valueOf(errorCode_);
        return result == null ? ErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 错误code
       * </pre>
       *
       * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        errorCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误code
       * </pre>
       *
       * <code>.RouteApiRes.ErrorCode errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private Object errorMsg_ = "";
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return The errorMsg.
       */
      public String getErrorMsg() {
        Object ref = errorMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return The bytes for errorMsg.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息
       * </pre>
       *
       * <code>string errorMsg = 2;</code>
       * @param value The bytes for errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }

      private boolean createTopicMetadataRes_ ;
      /**
       * <pre>
       * topic元数据创建结果
       * </pre>
       *
       * <code>bool createTopicMetadataRes = 3;</code>
       * @return The createTopicMetadataRes.
       */
      @Override
      public boolean getCreateTopicMetadataRes() {
        return createTopicMetadataRes_;
      }
      /**
       * <pre>
       * topic元数据创建结果
       * </pre>
       *
       * <code>bool createTopicMetadataRes = 3;</code>
       * @param value The createTopicMetadataRes to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTopicMetadataRes(boolean value) {
        
        createTopicMetadataRes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * topic元数据创建结果
       * </pre>
       *
       * <code>bool createTopicMetadataRes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTopicMetadataRes() {
        
        createTopicMetadataRes_ = false;
        onChanged();
        return this;
      }

      private FetchTopicMetadataResultWrapper.FetchTopicMetadataResult fetchTopicMetadataResult_;
      private com.google.protobuf.SingleFieldBuilderV3<
          FetchTopicMetadataResultWrapper.FetchTopicMetadataResult, FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.Builder, FetchTopicMetadataResultWrapper.FetchTopicMetadataResultOrBuilder> fetchTopicMetadataResultBuilder_;
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       * @return Whether the fetchTopicMetadataResult field is set.
       */
      public boolean hasFetchTopicMetadataResult() {
        return fetchTopicMetadataResultBuilder_ != null || fetchTopicMetadataResult_ != null;
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       * @return The fetchTopicMetadataResult.
       */
      public FetchTopicMetadataResultWrapper.FetchTopicMetadataResult getFetchTopicMetadataResult() {
        if (fetchTopicMetadataResultBuilder_ == null) {
          return fetchTopicMetadataResult_ == null ? FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.getDefaultInstance() : fetchTopicMetadataResult_;
        } else {
          return fetchTopicMetadataResultBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       */
      public Builder setFetchTopicMetadataResult(FetchTopicMetadataResultWrapper.FetchTopicMetadataResult value) {
        if (fetchTopicMetadataResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fetchTopicMetadataResult_ = value;
          onChanged();
        } else {
          fetchTopicMetadataResultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       */
      public Builder setFetchTopicMetadataResult(
          FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.Builder builderForValue) {
        if (fetchTopicMetadataResultBuilder_ == null) {
          fetchTopicMetadataResult_ = builderForValue.build();
          onChanged();
        } else {
          fetchTopicMetadataResultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       */
      public Builder mergeFetchTopicMetadataResult(FetchTopicMetadataResultWrapper.FetchTopicMetadataResult value) {
        if (fetchTopicMetadataResultBuilder_ == null) {
          if (fetchTopicMetadataResult_ != null) {
            fetchTopicMetadataResult_ =
              FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.newBuilder(fetchTopicMetadataResult_).mergeFrom(value).buildPartial();
          } else {
            fetchTopicMetadataResult_ = value;
          }
          onChanged();
        } else {
          fetchTopicMetadataResultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       */
      public Builder clearFetchTopicMetadataResult() {
        if (fetchTopicMetadataResultBuilder_ == null) {
          fetchTopicMetadataResult_ = null;
          onChanged();
        } else {
          fetchTopicMetadataResult_ = null;
          fetchTopicMetadataResultBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       */
      public FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.Builder getFetchTopicMetadataResultBuilder() {
        
        onChanged();
        return getFetchTopicMetadataResultFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       */
      public FetchTopicMetadataResultWrapper.FetchTopicMetadataResultOrBuilder getFetchTopicMetadataResultOrBuilder() {
        if (fetchTopicMetadataResultBuilder_ != null) {
          return fetchTopicMetadataResultBuilder_.getMessageOrBuilder();
        } else {
          return fetchTopicMetadataResult_ == null ?
              FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.getDefaultInstance() : fetchTopicMetadataResult_;
        }
      }
      /**
       * <pre>
       * 获取元数据的响应结果
       * </pre>
       *
       * <code>.FetchTopicMetadataResult fetchTopicMetadataResult = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FetchTopicMetadataResultWrapper.FetchTopicMetadataResult, FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.Builder, FetchTopicMetadataResultWrapper.FetchTopicMetadataResultOrBuilder> 
          getFetchTopicMetadataResultFieldBuilder() {
        if (fetchTopicMetadataResultBuilder_ == null) {
          fetchTopicMetadataResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FetchTopicMetadataResultWrapper.FetchTopicMetadataResult, FetchTopicMetadataResultWrapper.FetchTopicMetadataResult.Builder, FetchTopicMetadataResultWrapper.FetchTopicMetadataResultOrBuilder>(
                  getFetchTopicMetadataResult(),
                  getParentForChildren(),
                  isClean());
          fetchTopicMetadataResult_ = null;
        }
        return fetchTopicMetadataResultBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RouteApiRes)
    }

    // @@protoc_insertion_point(class_scope:RouteApiRes)
    private static final RouteApiRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RouteApiRes();
    }

    public static RouteApiRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RouteApiRes>
        PARSER = new com.google.protobuf.AbstractParser<RouteApiRes>() {
      @Override
      public RouteApiRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouteApiRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RouteApiRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RouteApiRes> getParserForType() {
      return PARSER;
    }

    @Override
    public RouteApiRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteApiRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteApiRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026RouteAPIResponse.proto\032\036FetchTopicMeta" +
      "dataResult.proto\"\341\001\n\013RouteApiRes\022)\n\terro" +
      "rCode\030\001 \001(\0162\026.RouteApiRes.ErrorCode\022\020\n\010e" +
      "rrorMsg\030\002 \001(\t\022\036\n\026createTopicMetadataRes\030" +
      "\003 \001(\010\022;\n\030fetchTopicMetadataResult\030\004 \001(\0132" +
      "\031.FetchTopicMetadataResult\"8\n\tErrorCode\022" +
      "\013\n\007UNKNOWN\020\000\022\036\n\032CREATE_TOPIC_METADATA_FA" +
      "IL\020\001B\021B\017RouteResWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          FetchTopicMetadataResultWrapper.getDescriptor(),
        });
    internal_static_RouteApiRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RouteApiRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteApiRes_descriptor,
        new String[] { "ErrorCode", "ErrorMsg", "CreateTopicMetadataRes", "FetchTopicMetadataResult", });
    FetchTopicMetadataResultWrapper.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
