package org.scalingmq.route.client.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteApiRequest.proto

public final class RouteReqWrapper {
  private RouteReqWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RouteReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RouteReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RouteReq.ReqType reqType = 1;</code>
     * @return The enum numeric value on the wire for reqType.
     */
    int getReqTypeValue();
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RouteReq.ReqType reqType = 1;</code>
     * @return The reqType.
     */
    RouteReq.ReqType getReqType();

    /**
     * <pre>
     * 获取topic元数据请求
     * </pre>
     *
     * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
     * @return Whether the fetchTopicMetadataReq field is set.
     */
    boolean hasFetchTopicMetadataReq();
    /**
     * <pre>
     * 获取topic元数据请求
     * </pre>
     *
     * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
     * @return The fetchTopicMetadataReq.
     */
    FetchTopicMetadataReqWrapper.FetchTopicMetadataReq getFetchTopicMetadataReq();
    /**
     * <pre>
     * 获取topic元数据请求
     * </pre>
     *
     * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
     */
    FetchTopicMetadataReqWrapper.FetchTopicMetadataReqOrBuilder getFetchTopicMetadataReqOrBuilder();

    /**
     * <pre>
     * 创建topic元数据请求
     * </pre>
     *
     * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
     * @return Whether the putTopicMetadataReq field is set.
     */
    boolean hasPutTopicMetadataReq();
    /**
     * <pre>
     * 创建topic元数据请求
     * </pre>
     *
     * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
     * @return The putTopicMetadataReq.
     */
    PutTopicMetadataReqWrapper.PutTopicMetadataReq getPutTopicMetadataReq();
    /**
     * <pre>
     * 创建topic元数据请求
     * </pre>
     *
     * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
     */
    PutTopicMetadataReqWrapper.PutTopicMetadataReqOrBuilder getPutTopicMetadataReqOrBuilder();

    /**
     * <pre>
     * 调度创建存储pod请求
     * </pre>
     *
     * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
     * @return Whether the schedStoragePodReq field is set.
     */
    boolean hasSchedStoragePodReq();
    /**
     * <pre>
     * 调度创建存储pod请求
     * </pre>
     *
     * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
     * @return The schedStoragePodReq.
     */
    SchedStoragePodReqWrapper.SchedStoragePodReq getSchedStoragePodReq();
    /**
     * <pre>
     * 调度创建存储pod请求
     * </pre>
     *
     * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
     */
    SchedStoragePodReqWrapper.SchedStoragePodReqOrBuilder getSchedStoragePodReqOrBuilder();
  }
  /**
   * Protobuf type {@code RouteReq}
   */
  public static final class RouteReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RouteReq)
      RouteReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RouteReq.newBuilder() to construct.
    private RouteReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RouteReq() {
      reqType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RouteReq();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RouteReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              reqType_ = rawValue;
              break;
            }
            case 18: {
              FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.Builder subBuilder = null;
              if (fetchTopicMetadataReq_ != null) {
                subBuilder = fetchTopicMetadataReq_.toBuilder();
              }
              fetchTopicMetadataReq_ = input.readMessage(FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fetchTopicMetadataReq_);
                fetchTopicMetadataReq_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              PutTopicMetadataReqWrapper.PutTopicMetadataReq.Builder subBuilder = null;
              if (putTopicMetadataReq_ != null) {
                subBuilder = putTopicMetadataReq_.toBuilder();
              }
              putTopicMetadataReq_ = input.readMessage(PutTopicMetadataReqWrapper.PutTopicMetadataReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(putTopicMetadataReq_);
                putTopicMetadataReq_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              SchedStoragePodReqWrapper.SchedStoragePodReq.Builder subBuilder = null;
              if (schedStoragePodReq_ != null) {
                subBuilder = schedStoragePodReq_.toBuilder();
              }
              schedStoragePodReq_ = input.readMessage(SchedStoragePodReqWrapper.SchedStoragePodReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(schedStoragePodReq_);
                schedStoragePodReq_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouteReqWrapper.internal_static_RouteReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouteReqWrapper.internal_static_RouteReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RouteReq.class, Builder.class);
    }

    /**
     * Protobuf enum {@code RouteReq.ReqType}
     */
    public enum ReqType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 获取topic的元数据
       * </pre>
       *
       * <code>FETCH_TOPIC_METADATA = 0;</code>
       */
      FETCH_TOPIC_METADATA(0),
      /**
       * <pre>
       * 创建topic的元数据
       * </pre>
       *
       * <code>PUT_TOPIC_METADATA = 1;</code>
       */
      PUT_TOPIC_METADATA(1),
      /**
       * <pre>
       * 调度生成存储pod
       * </pre>
       *
       * <code>SCHED_STORAGE_POD = 2;</code>
       */
      SCHED_STORAGE_POD(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 获取topic的元数据
       * </pre>
       *
       * <code>FETCH_TOPIC_METADATA = 0;</code>
       */
      public static final int FETCH_TOPIC_METADATA_VALUE = 0;
      /**
       * <pre>
       * 创建topic的元数据
       * </pre>
       *
       * <code>PUT_TOPIC_METADATA = 1;</code>
       */
      public static final int PUT_TOPIC_METADATA_VALUE = 1;
      /**
       * <pre>
       * 调度生成存储pod
       * </pre>
       *
       * <code>SCHED_STORAGE_POD = 2;</code>
       */
      public static final int SCHED_STORAGE_POD_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ReqType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ReqType forNumber(int value) {
        switch (value) {
          case 0: return FETCH_TOPIC_METADATA;
          case 1: return PUT_TOPIC_METADATA;
          case 2: return SCHED_STORAGE_POD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ReqType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ReqType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ReqType>() {
              public ReqType findValueByNumber(int number) {
                return ReqType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RouteReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final ReqType[] VALUES = values();

      public static ReqType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ReqType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RouteReq.ReqType)
    }

    public static final int REQTYPE_FIELD_NUMBER = 1;
    private int reqType_;
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RouteReq.ReqType reqType = 1;</code>
     * @return The enum numeric value on the wire for reqType.
     */
    @Override public int getReqTypeValue() {
      return reqType_;
    }
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RouteReq.ReqType reqType = 1;</code>
     * @return The reqType.
     */
    @Override public ReqType getReqType() {
      @SuppressWarnings("deprecation")
      ReqType result = ReqType.valueOf(reqType_);
      return result == null ? ReqType.UNRECOGNIZED : result;
    }

    public static final int FETCHTOPICMETADATAREQ_FIELD_NUMBER = 2;
    private FetchTopicMetadataReqWrapper.FetchTopicMetadataReq fetchTopicMetadataReq_;
    /**
     * <pre>
     * 获取topic元数据请求
     * </pre>
     *
     * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
     * @return Whether the fetchTopicMetadataReq field is set.
     */
    @Override
    public boolean hasFetchTopicMetadataReq() {
      return fetchTopicMetadataReq_ != null;
    }
    /**
     * <pre>
     * 获取topic元数据请求
     * </pre>
     *
     * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
     * @return The fetchTopicMetadataReq.
     */
    @Override
    public FetchTopicMetadataReqWrapper.FetchTopicMetadataReq getFetchTopicMetadataReq() {
      return fetchTopicMetadataReq_ == null ? FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.getDefaultInstance() : fetchTopicMetadataReq_;
    }
    /**
     * <pre>
     * 获取topic元数据请求
     * </pre>
     *
     * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
     */
    @Override
    public FetchTopicMetadataReqWrapper.FetchTopicMetadataReqOrBuilder getFetchTopicMetadataReqOrBuilder() {
      return getFetchTopicMetadataReq();
    }

    public static final int PUTTOPICMETADATAREQ_FIELD_NUMBER = 3;
    private PutTopicMetadataReqWrapper.PutTopicMetadataReq putTopicMetadataReq_;
    /**
     * <pre>
     * 创建topic元数据请求
     * </pre>
     *
     * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
     * @return Whether the putTopicMetadataReq field is set.
     */
    @Override
    public boolean hasPutTopicMetadataReq() {
      return putTopicMetadataReq_ != null;
    }
    /**
     * <pre>
     * 创建topic元数据请求
     * </pre>
     *
     * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
     * @return The putTopicMetadataReq.
     */
    @Override
    public PutTopicMetadataReqWrapper.PutTopicMetadataReq getPutTopicMetadataReq() {
      return putTopicMetadataReq_ == null ? PutTopicMetadataReqWrapper.PutTopicMetadataReq.getDefaultInstance() : putTopicMetadataReq_;
    }
    /**
     * <pre>
     * 创建topic元数据请求
     * </pre>
     *
     * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
     */
    @Override
    public PutTopicMetadataReqWrapper.PutTopicMetadataReqOrBuilder getPutTopicMetadataReqOrBuilder() {
      return getPutTopicMetadataReq();
    }

    public static final int SCHEDSTORAGEPODREQ_FIELD_NUMBER = 4;
    private SchedStoragePodReqWrapper.SchedStoragePodReq schedStoragePodReq_;
    /**
     * <pre>
     * 调度创建存储pod请求
     * </pre>
     *
     * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
     * @return Whether the schedStoragePodReq field is set.
     */
    @Override
    public boolean hasSchedStoragePodReq() {
      return schedStoragePodReq_ != null;
    }
    /**
     * <pre>
     * 调度创建存储pod请求
     * </pre>
     *
     * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
     * @return The schedStoragePodReq.
     */
    @Override
    public SchedStoragePodReqWrapper.SchedStoragePodReq getSchedStoragePodReq() {
      return schedStoragePodReq_ == null ? SchedStoragePodReqWrapper.SchedStoragePodReq.getDefaultInstance() : schedStoragePodReq_;
    }
    /**
     * <pre>
     * 调度创建存储pod请求
     * </pre>
     *
     * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
     */
    @Override
    public SchedStoragePodReqWrapper.SchedStoragePodReqOrBuilder getSchedStoragePodReqOrBuilder() {
      return getSchedStoragePodReq();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reqType_ != ReqType.FETCH_TOPIC_METADATA.getNumber()) {
        output.writeEnum(1, reqType_);
      }
      if (fetchTopicMetadataReq_ != null) {
        output.writeMessage(2, getFetchTopicMetadataReq());
      }
      if (putTopicMetadataReq_ != null) {
        output.writeMessage(3, getPutTopicMetadataReq());
      }
      if (schedStoragePodReq_ != null) {
        output.writeMessage(4, getSchedStoragePodReq());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reqType_ != ReqType.FETCH_TOPIC_METADATA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_);
      }
      if (fetchTopicMetadataReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFetchTopicMetadataReq());
      }
      if (putTopicMetadataReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPutTopicMetadataReq());
      }
      if (schedStoragePodReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSchedStoragePodReq());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RouteReq)) {
        return super.equals(obj);
      }
      RouteReq other = (RouteReq) obj;

      if (reqType_ != other.reqType_) return false;
      if (hasFetchTopicMetadataReq() != other.hasFetchTopicMetadataReq()) return false;
      if (hasFetchTopicMetadataReq()) {
        if (!getFetchTopicMetadataReq()
            .equals(other.getFetchTopicMetadataReq())) return false;
      }
      if (hasPutTopicMetadataReq() != other.hasPutTopicMetadataReq()) return false;
      if (hasPutTopicMetadataReq()) {
        if (!getPutTopicMetadataReq()
            .equals(other.getPutTopicMetadataReq())) return false;
      }
      if (hasSchedStoragePodReq() != other.hasSchedStoragePodReq()) return false;
      if (hasSchedStoragePodReq()) {
        if (!getSchedStoragePodReq()
            .equals(other.getSchedStoragePodReq())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
      hash = (53 * hash) + reqType_;
      if (hasFetchTopicMetadataReq()) {
        hash = (37 * hash) + FETCHTOPICMETADATAREQ_FIELD_NUMBER;
        hash = (53 * hash) + getFetchTopicMetadataReq().hashCode();
      }
      if (hasPutTopicMetadataReq()) {
        hash = (37 * hash) + PUTTOPICMETADATAREQ_FIELD_NUMBER;
        hash = (53 * hash) + getPutTopicMetadataReq().hashCode();
      }
      if (hasSchedStoragePodReq()) {
        hash = (37 * hash) + SCHEDSTORAGEPODREQ_FIELD_NUMBER;
        hash = (53 * hash) + getSchedStoragePodReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RouteReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RouteReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RouteReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RouteReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RouteReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RouteReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RouteReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RouteReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RouteReq)
        RouteReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RouteReqWrapper.internal_static_RouteReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RouteReqWrapper.internal_static_RouteReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RouteReq.class, Builder.class);
      }

      // Construct using RouteReqWrapper.RouteReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        reqType_ = 0;

        if (fetchTopicMetadataReqBuilder_ == null) {
          fetchTopicMetadataReq_ = null;
        } else {
          fetchTopicMetadataReq_ = null;
          fetchTopicMetadataReqBuilder_ = null;
        }
        if (putTopicMetadataReqBuilder_ == null) {
          putTopicMetadataReq_ = null;
        } else {
          putTopicMetadataReq_ = null;
          putTopicMetadataReqBuilder_ = null;
        }
        if (schedStoragePodReqBuilder_ == null) {
          schedStoragePodReq_ = null;
        } else {
          schedStoragePodReq_ = null;
          schedStoragePodReqBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RouteReqWrapper.internal_static_RouteReq_descriptor;
      }

      @Override
      public RouteReq getDefaultInstanceForType() {
        return RouteReq.getDefaultInstance();
      }

      @Override
      public RouteReq build() {
        RouteReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RouteReq buildPartial() {
        RouteReq result = new RouteReq(this);
        result.reqType_ = reqType_;
        if (fetchTopicMetadataReqBuilder_ == null) {
          result.fetchTopicMetadataReq_ = fetchTopicMetadataReq_;
        } else {
          result.fetchTopicMetadataReq_ = fetchTopicMetadataReqBuilder_.build();
        }
        if (putTopicMetadataReqBuilder_ == null) {
          result.putTopicMetadataReq_ = putTopicMetadataReq_;
        } else {
          result.putTopicMetadataReq_ = putTopicMetadataReqBuilder_.build();
        }
        if (schedStoragePodReqBuilder_ == null) {
          result.schedStoragePodReq_ = schedStoragePodReq_;
        } else {
          result.schedStoragePodReq_ = schedStoragePodReqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RouteReq) {
          return mergeFrom((RouteReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RouteReq other) {
        if (other == RouteReq.getDefaultInstance()) return this;
        if (other.reqType_ != 0) {
          setReqTypeValue(other.getReqTypeValue());
        }
        if (other.hasFetchTopicMetadataReq()) {
          mergeFetchTopicMetadataReq(other.getFetchTopicMetadataReq());
        }
        if (other.hasPutTopicMetadataReq()) {
          mergePutTopicMetadataReq(other.getPutTopicMetadataReq());
        }
        if (other.hasSchedStoragePodReq()) {
          mergeSchedStoragePodReq(other.getSchedStoragePodReq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RouteReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RouteReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int reqType_ = 0;
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RouteReq.ReqType reqType = 1;</code>
       * @return The enum numeric value on the wire for reqType.
       */
      @Override public int getReqTypeValue() {
        return reqType_;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RouteReq.ReqType reqType = 1;</code>
       * @param value The enum numeric value on the wire for reqType to set.
       * @return This builder for chaining.
       */
      public Builder setReqTypeValue(int value) {
        
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RouteReq.ReqType reqType = 1;</code>
       * @return The reqType.
       */
      @Override
      public ReqType getReqType() {
        @SuppressWarnings("deprecation")
        ReqType result = ReqType.valueOf(reqType_);
        return result == null ? ReqType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RouteReq.ReqType reqType = 1;</code>
       * @param value The reqType to set.
       * @return This builder for chaining.
       */
      public Builder setReqType(ReqType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        reqType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RouteReq.ReqType reqType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqType() {
        
        reqType_ = 0;
        onChanged();
        return this;
      }

      private FetchTopicMetadataReqWrapper.FetchTopicMetadataReq fetchTopicMetadataReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          FetchTopicMetadataReqWrapper.FetchTopicMetadataReq, FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.Builder, FetchTopicMetadataReqWrapper.FetchTopicMetadataReqOrBuilder> fetchTopicMetadataReqBuilder_;
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       * @return Whether the fetchTopicMetadataReq field is set.
       */
      public boolean hasFetchTopicMetadataReq() {
        return fetchTopicMetadataReqBuilder_ != null || fetchTopicMetadataReq_ != null;
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       * @return The fetchTopicMetadataReq.
       */
      public FetchTopicMetadataReqWrapper.FetchTopicMetadataReq getFetchTopicMetadataReq() {
        if (fetchTopicMetadataReqBuilder_ == null) {
          return fetchTopicMetadataReq_ == null ? FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.getDefaultInstance() : fetchTopicMetadataReq_;
        } else {
          return fetchTopicMetadataReqBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       */
      public Builder setFetchTopicMetadataReq(FetchTopicMetadataReqWrapper.FetchTopicMetadataReq value) {
        if (fetchTopicMetadataReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fetchTopicMetadataReq_ = value;
          onChanged();
        } else {
          fetchTopicMetadataReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       */
      public Builder setFetchTopicMetadataReq(
          FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.Builder builderForValue) {
        if (fetchTopicMetadataReqBuilder_ == null) {
          fetchTopicMetadataReq_ = builderForValue.build();
          onChanged();
        } else {
          fetchTopicMetadataReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       */
      public Builder mergeFetchTopicMetadataReq(FetchTopicMetadataReqWrapper.FetchTopicMetadataReq value) {
        if (fetchTopicMetadataReqBuilder_ == null) {
          if (fetchTopicMetadataReq_ != null) {
            fetchTopicMetadataReq_ =
              FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.newBuilder(fetchTopicMetadataReq_).mergeFrom(value).buildPartial();
          } else {
            fetchTopicMetadataReq_ = value;
          }
          onChanged();
        } else {
          fetchTopicMetadataReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       */
      public Builder clearFetchTopicMetadataReq() {
        if (fetchTopicMetadataReqBuilder_ == null) {
          fetchTopicMetadataReq_ = null;
          onChanged();
        } else {
          fetchTopicMetadataReq_ = null;
          fetchTopicMetadataReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       */
      public FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.Builder getFetchTopicMetadataReqBuilder() {
        
        onChanged();
        return getFetchTopicMetadataReqFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       */
      public FetchTopicMetadataReqWrapper.FetchTopicMetadataReqOrBuilder getFetchTopicMetadataReqOrBuilder() {
        if (fetchTopicMetadataReqBuilder_ != null) {
          return fetchTopicMetadataReqBuilder_.getMessageOrBuilder();
        } else {
          return fetchTopicMetadataReq_ == null ?
              FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.getDefaultInstance() : fetchTopicMetadataReq_;
        }
      }
      /**
       * <pre>
       * 获取topic元数据请求
       * </pre>
       *
       * <code>.FetchTopicMetadataReq fetchTopicMetadataReq = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FetchTopicMetadataReqWrapper.FetchTopicMetadataReq, FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.Builder, FetchTopicMetadataReqWrapper.FetchTopicMetadataReqOrBuilder> 
          getFetchTopicMetadataReqFieldBuilder() {
        if (fetchTopicMetadataReqBuilder_ == null) {
          fetchTopicMetadataReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FetchTopicMetadataReqWrapper.FetchTopicMetadataReq, FetchTopicMetadataReqWrapper.FetchTopicMetadataReq.Builder, FetchTopicMetadataReqWrapper.FetchTopicMetadataReqOrBuilder>(
                  getFetchTopicMetadataReq(),
                  getParentForChildren(),
                  isClean());
          fetchTopicMetadataReq_ = null;
        }
        return fetchTopicMetadataReqBuilder_;
      }

      private PutTopicMetadataReqWrapper.PutTopicMetadataReq putTopicMetadataReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          PutTopicMetadataReqWrapper.PutTopicMetadataReq, PutTopicMetadataReqWrapper.PutTopicMetadataReq.Builder, PutTopicMetadataReqWrapper.PutTopicMetadataReqOrBuilder> putTopicMetadataReqBuilder_;
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       * @return Whether the putTopicMetadataReq field is set.
       */
      public boolean hasPutTopicMetadataReq() {
        return putTopicMetadataReqBuilder_ != null || putTopicMetadataReq_ != null;
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       * @return The putTopicMetadataReq.
       */
      public PutTopicMetadataReqWrapper.PutTopicMetadataReq getPutTopicMetadataReq() {
        if (putTopicMetadataReqBuilder_ == null) {
          return putTopicMetadataReq_ == null ? PutTopicMetadataReqWrapper.PutTopicMetadataReq.getDefaultInstance() : putTopicMetadataReq_;
        } else {
          return putTopicMetadataReqBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       */
      public Builder setPutTopicMetadataReq(PutTopicMetadataReqWrapper.PutTopicMetadataReq value) {
        if (putTopicMetadataReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          putTopicMetadataReq_ = value;
          onChanged();
        } else {
          putTopicMetadataReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       */
      public Builder setPutTopicMetadataReq(
          PutTopicMetadataReqWrapper.PutTopicMetadataReq.Builder builderForValue) {
        if (putTopicMetadataReqBuilder_ == null) {
          putTopicMetadataReq_ = builderForValue.build();
          onChanged();
        } else {
          putTopicMetadataReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       */
      public Builder mergePutTopicMetadataReq(PutTopicMetadataReqWrapper.PutTopicMetadataReq value) {
        if (putTopicMetadataReqBuilder_ == null) {
          if (putTopicMetadataReq_ != null) {
            putTopicMetadataReq_ =
              PutTopicMetadataReqWrapper.PutTopicMetadataReq.newBuilder(putTopicMetadataReq_).mergeFrom(value).buildPartial();
          } else {
            putTopicMetadataReq_ = value;
          }
          onChanged();
        } else {
          putTopicMetadataReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       */
      public Builder clearPutTopicMetadataReq() {
        if (putTopicMetadataReqBuilder_ == null) {
          putTopicMetadataReq_ = null;
          onChanged();
        } else {
          putTopicMetadataReq_ = null;
          putTopicMetadataReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       */
      public PutTopicMetadataReqWrapper.PutTopicMetadataReq.Builder getPutTopicMetadataReqBuilder() {
        
        onChanged();
        return getPutTopicMetadataReqFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       */
      public PutTopicMetadataReqWrapper.PutTopicMetadataReqOrBuilder getPutTopicMetadataReqOrBuilder() {
        if (putTopicMetadataReqBuilder_ != null) {
          return putTopicMetadataReqBuilder_.getMessageOrBuilder();
        } else {
          return putTopicMetadataReq_ == null ?
              PutTopicMetadataReqWrapper.PutTopicMetadataReq.getDefaultInstance() : putTopicMetadataReq_;
        }
      }
      /**
       * <pre>
       * 创建topic元数据请求
       * </pre>
       *
       * <code>.PutTopicMetadataReq putTopicMetadataReq = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PutTopicMetadataReqWrapper.PutTopicMetadataReq, PutTopicMetadataReqWrapper.PutTopicMetadataReq.Builder, PutTopicMetadataReqWrapper.PutTopicMetadataReqOrBuilder> 
          getPutTopicMetadataReqFieldBuilder() {
        if (putTopicMetadataReqBuilder_ == null) {
          putTopicMetadataReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PutTopicMetadataReqWrapper.PutTopicMetadataReq, PutTopicMetadataReqWrapper.PutTopicMetadataReq.Builder, PutTopicMetadataReqWrapper.PutTopicMetadataReqOrBuilder>(
                  getPutTopicMetadataReq(),
                  getParentForChildren(),
                  isClean());
          putTopicMetadataReq_ = null;
        }
        return putTopicMetadataReqBuilder_;
      }

      private SchedStoragePodReqWrapper.SchedStoragePodReq schedStoragePodReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          SchedStoragePodReqWrapper.SchedStoragePodReq, SchedStoragePodReqWrapper.SchedStoragePodReq.Builder, SchedStoragePodReqWrapper.SchedStoragePodReqOrBuilder> schedStoragePodReqBuilder_;
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       * @return Whether the schedStoragePodReq field is set.
       */
      public boolean hasSchedStoragePodReq() {
        return schedStoragePodReqBuilder_ != null || schedStoragePodReq_ != null;
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       * @return The schedStoragePodReq.
       */
      public SchedStoragePodReqWrapper.SchedStoragePodReq getSchedStoragePodReq() {
        if (schedStoragePodReqBuilder_ == null) {
          return schedStoragePodReq_ == null ? SchedStoragePodReqWrapper.SchedStoragePodReq.getDefaultInstance() : schedStoragePodReq_;
        } else {
          return schedStoragePodReqBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       */
      public Builder setSchedStoragePodReq(SchedStoragePodReqWrapper.SchedStoragePodReq value) {
        if (schedStoragePodReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          schedStoragePodReq_ = value;
          onChanged();
        } else {
          schedStoragePodReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       */
      public Builder setSchedStoragePodReq(
          SchedStoragePodReqWrapper.SchedStoragePodReq.Builder builderForValue) {
        if (schedStoragePodReqBuilder_ == null) {
          schedStoragePodReq_ = builderForValue.build();
          onChanged();
        } else {
          schedStoragePodReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       */
      public Builder mergeSchedStoragePodReq(SchedStoragePodReqWrapper.SchedStoragePodReq value) {
        if (schedStoragePodReqBuilder_ == null) {
          if (schedStoragePodReq_ != null) {
            schedStoragePodReq_ =
              SchedStoragePodReqWrapper.SchedStoragePodReq.newBuilder(schedStoragePodReq_).mergeFrom(value).buildPartial();
          } else {
            schedStoragePodReq_ = value;
          }
          onChanged();
        } else {
          schedStoragePodReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       */
      public Builder clearSchedStoragePodReq() {
        if (schedStoragePodReqBuilder_ == null) {
          schedStoragePodReq_ = null;
          onChanged();
        } else {
          schedStoragePodReq_ = null;
          schedStoragePodReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       */
      public SchedStoragePodReqWrapper.SchedStoragePodReq.Builder getSchedStoragePodReqBuilder() {
        
        onChanged();
        return getSchedStoragePodReqFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       */
      public SchedStoragePodReqWrapper.SchedStoragePodReqOrBuilder getSchedStoragePodReqOrBuilder() {
        if (schedStoragePodReqBuilder_ != null) {
          return schedStoragePodReqBuilder_.getMessageOrBuilder();
        } else {
          return schedStoragePodReq_ == null ?
              SchedStoragePodReqWrapper.SchedStoragePodReq.getDefaultInstance() : schedStoragePodReq_;
        }
      }
      /**
       * <pre>
       * 调度创建存储pod请求
       * </pre>
       *
       * <code>.SchedStoragePodReq schedStoragePodReq = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SchedStoragePodReqWrapper.SchedStoragePodReq, SchedStoragePodReqWrapper.SchedStoragePodReq.Builder, SchedStoragePodReqWrapper.SchedStoragePodReqOrBuilder> 
          getSchedStoragePodReqFieldBuilder() {
        if (schedStoragePodReqBuilder_ == null) {
          schedStoragePodReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SchedStoragePodReqWrapper.SchedStoragePodReq, SchedStoragePodReqWrapper.SchedStoragePodReq.Builder, SchedStoragePodReqWrapper.SchedStoragePodReqOrBuilder>(
                  getSchedStoragePodReq(),
                  getParentForChildren(),
                  isClean());
          schedStoragePodReq_ = null;
        }
        return schedStoragePodReqBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RouteReq)
    }

    // @@protoc_insertion_point(class_scope:RouteReq)
    private static final RouteReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RouteReq();
    }

    public static RouteReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RouteReq>
        PARSER = new com.google.protobuf.AbstractParser<RouteReq>() {
      @Override
      public RouteReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouteReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RouteReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RouteReq> getParserForType() {
      return PARSER;
    }

    @Override
    public RouteReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025RouteApiRequest.proto\032\033FetchTopicMetad" +
      "ataReq.proto\032\031PutTopicMetadataReq.proto\032" +
      "\030SchedStoragePodReq.proto\"\235\002\n\010RouteReq\022\"" +
      "\n\007reqType\030\001 \001(\0162\021.RouteReq.ReqType\0225\n\025fe" +
      "tchTopicMetadataReq\030\002 \001(\0132\026.FetchTopicMe" +
      "tadataReq\0221\n\023putTopicMetadataReq\030\003 \001(\0132\024" +
      ".PutTopicMetadataReq\022/\n\022schedStoragePodR" +
      "eq\030\004 \001(\0132\023.SchedStoragePodReq\"R\n\007ReqType" +
      "\022\030\n\024FETCH_TOPIC_METADATA\020\000\022\026\n\022PUT_TOPIC_" +
      "METADATA\020\001\022\025\n\021SCHED_STORAGE_POD\020\002B\021B\017Rou" +
      "teReqWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          FetchTopicMetadataReqWrapper.getDescriptor(),
          PutTopicMetadataReqWrapper.getDescriptor(),
          SchedStoragePodReqWrapper.getDescriptor(),
        });
    internal_static_RouteReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RouteReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteReq_descriptor,
        new String[] { "ReqType", "FetchTopicMetadataReq", "PutTopicMetadataReq", "SchedStoragePodReq", });
    FetchTopicMetadataReqWrapper.getDescriptor();
    PutTopicMetadataReqWrapper.getDescriptor();
    SchedStoragePodReqWrapper.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
