apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scalingmq-storage-csi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: org.scalingmq.csi.storage.class