---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scalingmq-storage-csi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: org.scalingmq.csi.storage.class
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-test-pod
  labels:
    app: csi-test-pod
spec:
  containers:
    - name: csi-test-pod
      image: nginx:1.8
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-pvc
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: scalingmq-storage-csi-pvc
  restartPolicy: Always

